/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DebugHostRouteImport } from './routes/debug-host'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as ApiMenuSyncRouteImport } from './routes/api/menu-sync'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as ZecarretoIndexRouteImport } from './routes/zecarreto.index'
import { Route as ZecarretoAdminRouteImport } from './routes/zecarreto.admin'
import { Route as ZecarretoContaRouteImport } from './routes/zecarreto.conta'
import { Route as ZecarretoEnderecosRouteImport } from './routes/zecarreto.enderecos'
import { Route as ZecarretoEntrarRouteImport } from './routes/zecarreto.entrar'
import { Route as ZecarretoMotoristaRouteImport } from './routes/zecarreto.motorista'
import { Route as ZecarretoPedirRouteImport } from './routes/zecarreto.pedir'
import { Route as AuthenticatedEditIdRouteImport } from './routes/_authenticated.edit.$id'
import { Route as AuthenticatedExportIdRouteImport } from './routes/_authenticated.export.$id'
import { Route as ApiInternalDeprovisionRestaurantRouteImport } from './routes/api/internal/deprovision-restaurant'
import { Route as ApiInternalProvisionRestaurantRouteImport } from './routes/api/internal/provision-restaurant'
import { Route as ApiMenuSyncSplatRouteImport } from './routes/api/menu-sync.$'
import { Route as ApiPublicCheckTableSessionRouteImport } from './routes/api/public/check-table-session'
import { Route as ApiPublicFlycontrolTableClosedRouteImport } from './routes/api/public/flycontrol-table-closed'
import { Route as ApiPublicOpenTableSessionRouteImport } from './routes/api/public/open-table-session'
import { Route as ApiPublicRequestCloseTableRouteImport } from './routes/api/public/request-close-table'
import { Route as ApiPublicSubmitOrderRouteImport } from './routes/api/public/submit-order'
import { Route as ApiZecarretoCatalogRouteImport } from './routes/api/zecarreto/catalog'
import { Route as ApiZecarretoGeocodeRouteImport } from './routes/api/zecarreto/geocode'
import { Route as ApiZecarretoNotificationsRouteImport } from './routes/api/zecarreto/notifications'
import { Route as ApiZecarretoOffersRouteImport } from './routes/api/zecarreto/offers'
import { Route as ApiZecarretoPayoutsRouteImport } from './routes/api/zecarreto/payouts'
import { Route as ApiZecarretoQuotesRouteImport } from './routes/api/zecarreto/quotes'
import { Route as ApiZecarretoRecommendRouteImport } from './routes/api/zecarreto/recommend'
import { Route as ApiZecarretoRidesRouteImport } from './routes/api/zecarreto/rides'
import { Route as ApiZecarretoWalletRouteImport } from './routes/api/zecarreto/wallet'
import { Route as ZecarretoAcompanharTokenRouteImport } from './routes/zecarreto.acompanhar.$token'
import { Route as ZecarretoAdminPrecosRouteImport } from './routes/zecarreto.admin.precos'
import { Route as ZecarretoMotoristaTrabalhoRouteImport } from './routes/zecarreto.motorista.trabalho'
import { Route as ZecarretoMotoristaVeiculosRouteImport } from './routes/zecarreto.motorista.veiculos'
import { Route as ZecarretoPedidoRideIdRouteImport } from './routes/zecarreto.pedido.$rideId'
import { Route as ApiZecarretoAdminAddonsRouteImport } from './routes/api/zecarreto/admin.addons'
import { Route as ApiZecarretoAdminDocumentsRouteImport } from './routes/api/zecarreto/admin.documents'
import { Route as ApiZecarretoAdminDriversRouteImport } from './routes/api/zecarreto/admin.drivers'
import { Route as ApiZecarretoAdminHistoryRouteImport } from './routes/api/zecarreto/admin.history'
import { Route as ApiZecarretoAdminRidesRouteImport } from './routes/api/zecarreto/admin.rides'
import { Route as ApiZecarretoAdminSettingsRouteImport } from './routes/api/zecarreto/admin.settings'
import { Route as ApiZecarretoAdminTariffsRouteImport } from './routes/api/zecarreto/admin.tariffs'
import { Route as ApiZecarretoAdminVehiclesRouteImport } from './routes/api/zecarreto/admin.vehicles'
import { Route as ApiZecarretoAuthConfigRouteImport } from './routes/api/zecarreto/auth.config'
import { Route as ApiZecarretoDriversMeRouteImport } from './routes/api/zecarreto/drivers.me'
import { Route as ApiZecarretoProfileAddressesRouteImport } from './routes/api/zecarreto/profile.addresses'
import { Route as ApiZecarretoProfileMeRouteImport } from './routes/api/zecarreto/profile.me'
import { Route as ApiZecarretoProfileRoleRouteImport } from './routes/api/zecarreto/profile.role'
import { Route as ApiZecarretoProfileTermsRouteImport } from './routes/api/zecarreto/profile.terms'
import { Route as ApiZecarretoRidesRideIdRouteImport } from './routes/api/zecarreto/rides.$rideId'
import { Route as ApiZecarretoSupportTicketsRouteImport } from './routes/api/zecarreto/support.tickets'
import { Route as ApiZecarretoTrackTokenRouteImport } from './routes/api/zecarreto/track.$token'
import { Route as ApiZecarretoUploadsSignRouteImport } from './routes/api/zecarreto/uploads.sign'
import { Route as ApiZecarretoWebhooksPaymentRouteImport } from './routes/api/zecarreto/webhooks.payment'
import { Route as ApiPublicMenuSyncSlugTokenRouteImport } from './routes/api.public.menu-sync.$slug.$token'
import { Route as ApiPublicPizzeriasSlugMenuSyncRouteImport } from './routes/api.public.pizzerias.$slug.menu-sync'
import { Route as ApiZecarretoAdminDispatchRecoverRouteImport } from './routes/api/zecarreto/admin.dispatch.recover'
import { Route as ApiZecarretoAdminDispatchTickRouteImport } from './routes/api/zecarreto/admin.dispatch.tick'
import { Route as ApiZecarretoAdminDriversDriverIdRouteImport } from './routes/api/zecarreto/admin.drivers.$driverId'
import { Route as ApiZecarretoAdminPayoutsPayoutIdRouteImport } from './routes/api/zecarreto/admin.payouts.$payoutId'
import { Route as ApiZecarretoAdminPayoutsCloseRouteImport } from './routes/api/zecarreto/admin.payouts.close'
import { Route as ApiZecarretoDriversMeAvailabilityRouteImport } from './routes/api/zecarreto/drivers.me.availability'
import { Route as ApiZecarretoDriversMeCurrentRouteImport } from './routes/api/zecarreto/drivers.me.current'
import { Route as ApiZecarretoDriversMeDocumentsRouteImport } from './routes/api/zecarreto/drivers.me.documents'
import { Route as ApiZecarretoDriversMeLocationRouteImport } from './routes/api/zecarreto/drivers.me.location'
import { Route as ApiZecarretoDriversMeSubmitRouteImport } from './routes/api/zecarreto/drivers.me.submit'
import { Route as ApiZecarretoDriversMeVehiclesRouteImport } from './routes/api/zecarreto/drivers.me.vehicles'
import { Route as ApiZecarretoOffersOfferIdRespondRouteImport } from './routes/api/zecarreto/offers.$offerId.respond'
import { Route as ApiZecarretoProfileAddressesAddressIdRouteImport } from './routes/api/zecarreto/profile.addresses.$addressId'
import { Route as ApiZecarretoRidesRideIdCancelRouteImport } from './routes/api/zecarreto/rides.$rideId.cancel'
import { Route as ApiZecarretoRidesRideIdMessagesRouteImport } from './routes/api/zecarreto/rides.$rideId.messages'
import { Route as ApiZecarretoRidesRideIdPaymentRouteImport } from './routes/api/zecarreto/rides.$rideId.payment'
import { Route as ApiZecarretoRidesRideIdRatingRouteImport } from './routes/api/zecarreto/rides.$rideId.rating'
import { Route as ApiZecarretoRidesRideIdReleaseRouteImport } from './routes/api/zecarreto/rides.$rideId.release'
import { Route as ApiZecarretoRidesRideIdShareRouteImport } from './routes/api/zecarreto/rides.$rideId.share'
import { Route as ApiZecarretoRidesRideIdStatusRouteImport } from './routes/api/zecarreto/rides.$rideId.status'
import { Route as ApiZecarretoRidesRideIdTrackRouteImport } from './routes/api/zecarreto/rides.$rideId.track'
import { Route as ApiZecarretoSupportTicketsTicketIdRouteImport } from './routes/api/zecarreto/support.tickets.$ticketId'
import { Route as ApiZecarretoAdminDocumentsDocumentIdReviewRouteImport } from './routes/api/zecarreto/admin.documents.$documentId.review'
import { Route as ApiZecarretoAdminDriversDriverIdRevealRouteImport } from './routes/api/zecarreto/admin.drivers.$driverId.reveal'
import { Route as ApiZecarretoAdminDriversDriverIdReviewRouteImport } from './routes/api/zecarreto/admin.drivers.$driverId.review'
import { Route as ApiZecarretoAdminVehiclesVehicleIdReviewRouteImport } from './routes/api/zecarreto/admin.vehicles.$vehicleId.review'
import { Route as ApiZecarretoDriversMeVehiclesVehicleIdRouteImport } from './routes/api/zecarreto/drivers.me.vehicles.$vehicleId'

const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugHostRoute = DebugHostRouteImport.update({
  id: '/debug-host',
  path: '/debug-host',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiMenuSyncRoute = ApiMenuSyncRouteImport.update({
  id: '/api/menu-sync',
  path: '/api/menu-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ZecarretoIndexRoute = ZecarretoIndexRouteImport.update({
  id: '/zecarreto/',
  path: '/zecarreto/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZecarretoAdminRoute = ZecarretoAdminRouteImport.update({
  id: '/zecarreto/admin',
  path: '/zecarreto/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ZecarretoContaRoute = ZecarretoContaRouteImport.update({
  id: '/zecarreto/conta',
  path: '/zecarreto/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ZecarretoEnderecosRoute = ZecarretoEnderecosRouteImport.update({
  id: '/zecarreto/enderecos',
  path: '/zecarreto/enderecos',
  getParentRoute: () => rootRouteImport,
} as any)
const ZecarretoEntrarRoute = ZecarretoEntrarRouteImport.update({
  id: '/zecarreto/entrar',
  path: '/zecarreto/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ZecarretoMotoristaRoute = ZecarretoMotoristaRouteImport.update({
  id: '/zecarreto/motorista',
  path: '/zecarreto/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const ZecarretoPedirRoute = ZecarretoPedirRouteImport.update({
  id: '/zecarreto/pedir',
  path: '/zecarreto/pedir',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditIdRoute = AuthenticatedEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportIdRoute = AuthenticatedExportIdRouteImport.update({
  id: '/export/$id',
  path: '/export/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiInternalDeprovisionRestaurantRoute =
  ApiInternalDeprovisionRestaurantRouteImport.update({
    id: '/api/internal/deprovision-restaurant',
    path: '/api/internal/deprovision-restaurant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalProvisionRestaurantRoute =
  ApiInternalProvisionRestaurantRouteImport.update({
    id: '/api/internal/provision-restaurant',
    path: '/api/internal/provision-restaurant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMenuSyncSplatRoute = ApiMenuSyncSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiMenuSyncRoute,
} as any)
const ApiPublicCheckTableSessionRoute =
  ApiPublicCheckTableSessionRouteImport.update({
    id: '/api/public/check-table-session',
    path: '/api/public/check-table-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFlycontrolTableClosedRoute =
  ApiPublicFlycontrolTableClosedRouteImport.update({
    id: '/api/public/flycontrol-table-closed',
    path: '/api/public/flycontrol-table-closed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOpenTableSessionRoute =
  ApiPublicOpenTableSessionRouteImport.update({
    id: '/api/public/open-table-session',
    path: '/api/public/open-table-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRequestCloseTableRoute =
  ApiPublicRequestCloseTableRouteImport.update({
    id: '/api/public/request-close-table',
    path: '/api/public/request-close-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSubmitOrderRoute = ApiPublicSubmitOrderRouteImport.update({
  id: '/api/public/submit-order',
  path: '/api/public/submit-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoCatalogRoute = ApiZecarretoCatalogRouteImport.update({
  id: '/api/zecarreto/catalog',
  path: '/api/zecarreto/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoGeocodeRoute = ApiZecarretoGeocodeRouteImport.update({
  id: '/api/zecarreto/geocode',
  path: '/api/zecarreto/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoNotificationsRoute =
  ApiZecarretoNotificationsRouteImport.update({
    id: '/api/zecarreto/notifications',
    path: '/api/zecarreto/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoOffersRoute = ApiZecarretoOffersRouteImport.update({
  id: '/api/zecarreto/offers',
  path: '/api/zecarreto/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoPayoutsRoute = ApiZecarretoPayoutsRouteImport.update({
  id: '/api/zecarreto/payouts',
  path: '/api/zecarreto/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoQuotesRoute = ApiZecarretoQuotesRouteImport.update({
  id: '/api/zecarreto/quotes',
  path: '/api/zecarreto/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoRecommendRoute = ApiZecarretoRecommendRouteImport.update({
  id: '/api/zecarreto/recommend',
  path: '/api/zecarreto/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoRidesRoute = ApiZecarretoRidesRouteImport.update({
  id: '/api/zecarreto/rides',
  path: '/api/zecarreto/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoWalletRoute = ApiZecarretoWalletRouteImport.update({
  id: '/api/zecarreto/wallet',
  path: '/api/zecarreto/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ZecarretoAcompanharTokenRoute =
  ZecarretoAcompanharTokenRouteImport.update({
    id: '/zecarreto/acompanhar/$token',
    path: '/zecarreto/acompanhar/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ZecarretoAdminPrecosRoute = ZecarretoAdminPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => ZecarretoAdminRoute,
} as any)
const ZecarretoMotoristaTrabalhoRoute =
  ZecarretoMotoristaTrabalhoRouteImport.update({
    id: '/trabalho',
    path: '/trabalho',
    getParentRoute: () => ZecarretoMotoristaRoute,
  } as any)
const ZecarretoMotoristaVeiculosRoute =
  ZecarretoMotoristaVeiculosRouteImport.update({
    id: '/veiculos',
    path: '/veiculos',
    getParentRoute: () => ZecarretoMotoristaRoute,
  } as any)
const ZecarretoPedidoRideIdRoute = ZecarretoPedidoRideIdRouteImport.update({
  id: '/zecarreto/pedido/$rideId',
  path: '/zecarreto/pedido/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoAdminAddonsRoute = ApiZecarretoAdminAddonsRouteImport.update({
  id: '/api/zecarreto/admin/addons',
  path: '/api/zecarreto/admin/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoAdminDocumentsRoute =
  ApiZecarretoAdminDocumentsRouteImport.update({
    id: '/api/zecarreto/admin/documents',
    path: '/api/zecarreto/admin/documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAdminDriversRoute =
  ApiZecarretoAdminDriversRouteImport.update({
    id: '/api/zecarreto/admin/drivers',
    path: '/api/zecarreto/admin/drivers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAdminHistoryRoute =
  ApiZecarretoAdminHistoryRouteImport.update({
    id: '/api/zecarreto/admin/history',
    path: '/api/zecarreto/admin/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAdminRidesRoute = ApiZecarretoAdminRidesRouteImport.update({
  id: '/api/zecarreto/admin/rides',
  path: '/api/zecarreto/admin/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoAdminSettingsRoute =
  ApiZecarretoAdminSettingsRouteImport.update({
    id: '/api/zecarreto/admin/settings',
    path: '/api/zecarreto/admin/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAdminTariffsRoute =
  ApiZecarretoAdminTariffsRouteImport.update({
    id: '/api/zecarreto/admin/tariffs',
    path: '/api/zecarreto/admin/tariffs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAdminVehiclesRoute =
  ApiZecarretoAdminVehiclesRouteImport.update({
    id: '/api/zecarreto/admin/vehicles',
    path: '/api/zecarreto/admin/vehicles',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAuthConfigRoute = ApiZecarretoAuthConfigRouteImport.update({
  id: '/api/zecarreto/auth/config',
  path: '/api/zecarreto/auth/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoDriversMeRoute = ApiZecarretoDriversMeRouteImport.update({
  id: '/api/zecarreto/drivers/me',
  path: '/api/zecarreto/drivers/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoProfileAddressesRoute =
  ApiZecarretoProfileAddressesRouteImport.update({
    id: '/api/zecarreto/profile/addresses',
    path: '/api/zecarreto/profile/addresses',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoProfileMeRoute = ApiZecarretoProfileMeRouteImport.update({
  id: '/api/zecarreto/profile/me',
  path: '/api/zecarreto/profile/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoProfileRoleRoute = ApiZecarretoProfileRoleRouteImport.update({
  id: '/api/zecarreto/profile/role',
  path: '/api/zecarreto/profile/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoProfileTermsRoute =
  ApiZecarretoProfileTermsRouteImport.update({
    id: '/api/zecarreto/profile/terms',
    path: '/api/zecarreto/profile/terms',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoRidesRideIdRoute = ApiZecarretoRidesRideIdRouteImport.update({
  id: '/$rideId',
  path: '/$rideId',
  getParentRoute: () => ApiZecarretoRidesRoute,
} as any)
const ApiZecarretoSupportTicketsRoute =
  ApiZecarretoSupportTicketsRouteImport.update({
    id: '/api/zecarreto/support/tickets',
    path: '/api/zecarreto/support/tickets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoTrackTokenRoute = ApiZecarretoTrackTokenRouteImport.update({
  id: '/api/zecarreto/track/$token',
  path: '/api/zecarreto/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoUploadsSignRoute = ApiZecarretoUploadsSignRouteImport.update({
  id: '/api/zecarreto/uploads/sign',
  path: '/api/zecarreto/uploads/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZecarretoWebhooksPaymentRoute =
  ApiZecarretoWebhooksPaymentRouteImport.update({
    id: '/api/zecarreto/webhooks/payment',
    path: '/api/zecarreto/webhooks/payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMenuSyncSlugTokenRoute =
  ApiPublicMenuSyncSlugTokenRouteImport.update({
    id: '/api/public/menu-sync/$slug/$token',
    path: '/api/public/menu-sync/$slug/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPizzeriasSlugMenuSyncRoute =
  ApiPublicPizzeriasSlugMenuSyncRouteImport.update({
    id: '/api/public/pizzerias/$slug/menu-sync',
    path: '/api/public/pizzerias/$slug/menu-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAdminDispatchRecoverRoute =
  ApiZecarretoAdminDispatchRecoverRouteImport.update({
    id: '/api/zecarreto/admin/dispatch/recover',
    path: '/api/zecarreto/admin/dispatch/recover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAdminDispatchTickRoute =
  ApiZecarretoAdminDispatchTickRouteImport.update({
    id: '/api/zecarreto/admin/dispatch/tick',
    path: '/api/zecarreto/admin/dispatch/tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAdminDriversDriverIdRoute =
  ApiZecarretoAdminDriversDriverIdRouteImport.update({
    id: '/$driverId',
    path: '/$driverId',
    getParentRoute: () => ApiZecarretoAdminDriversRoute,
  } as any)
const ApiZecarretoAdminPayoutsPayoutIdRoute =
  ApiZecarretoAdminPayoutsPayoutIdRouteImport.update({
    id: '/api/zecarreto/admin/payouts/$payoutId',
    path: '/api/zecarreto/admin/payouts/$payoutId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoAdminPayoutsCloseRoute =
  ApiZecarretoAdminPayoutsCloseRouteImport.update({
    id: '/api/zecarreto/admin/payouts/close',
    path: '/api/zecarreto/admin/payouts/close',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiZecarretoDriversMeAvailabilityRoute =
  ApiZecarretoDriversMeAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => ApiZecarretoDriversMeRoute,
  } as any)
const ApiZecarretoDriversMeCurrentRoute =
  ApiZecarretoDriversMeCurrentRouteImport.update({
    id: '/current',
    path: '/current',
    getParentRoute: () => ApiZecarretoDriversMeRoute,
  } as any)
const ApiZecarretoDriversMeDocumentsRoute =
  ApiZecarretoDriversMeDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ApiZecarretoDriversMeRoute,
  } as any)
const ApiZecarretoDriversMeLocationRoute =
  ApiZecarretoDriversMeLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => ApiZecarretoDriversMeRoute,
  } as any)
const ApiZecarretoDriversMeSubmitRoute =
  ApiZecarretoDriversMeSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => ApiZecarretoDriversMeRoute,
  } as any)
const ApiZecarretoDriversMeVehiclesRoute =
  ApiZecarretoDriversMeVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => ApiZecarretoDriversMeRoute,
  } as any)
const ApiZecarretoOffersOfferIdRespondRoute =
  ApiZecarretoOffersOfferIdRespondRouteImport.update({
    id: '/$offerId/respond',
    path: '/$offerId/respond',
    getParentRoute: () => ApiZecarretoOffersRoute,
  } as any)
const ApiZecarretoProfileAddressesAddressIdRoute =
  ApiZecarretoProfileAddressesAddressIdRouteImport.update({
    id: '/$addressId',
    path: '/$addressId',
    getParentRoute: () => ApiZecarretoProfileAddressesRoute,
  } as any)
const ApiZecarretoRidesRideIdCancelRoute =
  ApiZecarretoRidesRideIdCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => ApiZecarretoRidesRideIdRoute,
  } as any)
const ApiZecarretoRidesRideIdMessagesRoute =
  ApiZecarretoRidesRideIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiZecarretoRidesRideIdRoute,
  } as any)
const ApiZecarretoRidesRideIdPaymentRoute =
  ApiZecarretoRidesRideIdPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => ApiZecarretoRidesRideIdRoute,
  } as any)
const ApiZecarretoRidesRideIdRatingRoute =
  ApiZecarretoRidesRideIdRatingRouteImport.update({
    id: '/rating',
    path: '/rating',
    getParentRoute: () => ApiZecarretoRidesRideIdRoute,
  } as any)
const ApiZecarretoRidesRideIdReleaseRoute =
  ApiZecarretoRidesRideIdReleaseRouteImport.update({
    id: '/release',
    path: '/release',
    getParentRoute: () => ApiZecarretoRidesRideIdRoute,
  } as any)
const ApiZecarretoRidesRideIdShareRoute =
  ApiZecarretoRidesRideIdShareRouteImport.update({
    id: '/share',
    path: '/share',
    getParentRoute: () => ApiZecarretoRidesRideIdRoute,
  } as any)
const ApiZecarretoRidesRideIdStatusRoute =
  ApiZecarretoRidesRideIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiZecarretoRidesRideIdRoute,
  } as any)
const ApiZecarretoRidesRideIdTrackRoute =
  ApiZecarretoRidesRideIdTrackRouteImport.update({
    id: '/track',
    path: '/track',
    getParentRoute: () => ApiZecarretoRidesRideIdRoute,
  } as any)
const ApiZecarretoSupportTicketsTicketIdRoute =
  ApiZecarretoSupportTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => ApiZecarretoSupportTicketsRoute,
  } as any)
const ApiZecarretoAdminDocumentsDocumentIdReviewRoute =
  ApiZecarretoAdminDocumentsDocumentIdReviewRouteImport.update({
    id: '/$documentId/review',
    path: '/$documentId/review',
    getParentRoute: () => ApiZecarretoAdminDocumentsRoute,
  } as any)
const ApiZecarretoAdminDriversDriverIdRevealRoute =
  ApiZecarretoAdminDriversDriverIdRevealRouteImport.update({
    id: '/reveal',
    path: '/reveal',
    getParentRoute: () => ApiZecarretoAdminDriversDriverIdRoute,
  } as any)
const ApiZecarretoAdminDriversDriverIdReviewRoute =
  ApiZecarretoAdminDriversDriverIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => ApiZecarretoAdminDriversDriverIdRoute,
  } as any)
const ApiZecarretoAdminVehiclesVehicleIdReviewRoute =
  ApiZecarretoAdminVehiclesVehicleIdReviewRouteImport.update({
    id: '/$vehicleId/review',
    path: '/$vehicleId/review',
    getParentRoute: () => ApiZecarretoAdminVehiclesRoute,
  } as any)
const ApiZecarretoDriversMeVehiclesVehicleIdRoute =
  ApiZecarretoDriversMeVehiclesVehicleIdRouteImport.update({
    id: '/$vehicleId',
    path: '/$vehicleId',
    getParentRoute: () => ApiZecarretoDriversMeVehiclesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$slug': typeof SlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/debug-host': typeof DebugHostRoute
  '/login': typeof LoginRoute
  '/api/menu-sync': typeof ApiMenuSyncRouteWithChildren
  '/api/upload-image': typeof ApiUploadImageRoute
  '/zecarreto/admin': typeof ZecarretoAdminRouteWithChildren
  '/zecarreto/conta': typeof ZecarretoContaRoute
  '/zecarreto/enderecos': typeof ZecarretoEnderecosRoute
  '/zecarreto/entrar': typeof ZecarretoEntrarRoute
  '/zecarreto/motorista': typeof ZecarretoMotoristaRouteWithChildren
  '/zecarreto/pedir': typeof ZecarretoPedirRoute
  '/zecarreto/': typeof ZecarretoIndexRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
  '/export/$id': typeof AuthenticatedExportIdRoute
  '/api/internal/deprovision-restaurant': typeof ApiInternalDeprovisionRestaurantRoute
  '/api/internal/provision-restaurant': typeof ApiInternalProvisionRestaurantRoute
  '/api/menu-sync/$': typeof ApiMenuSyncSplatRoute
  '/api/public/check-table-session': typeof ApiPublicCheckTableSessionRoute
  '/api/public/flycontrol-table-closed': typeof ApiPublicFlycontrolTableClosedRoute
  '/api/public/open-table-session': typeof ApiPublicOpenTableSessionRoute
  '/api/public/request-close-table': typeof ApiPublicRequestCloseTableRoute
  '/api/public/submit-order': typeof ApiPublicSubmitOrderRoute
  '/api/zecarreto/catalog': typeof ApiZecarretoCatalogRoute
  '/api/zecarreto/geocode': typeof ApiZecarretoGeocodeRoute
  '/api/zecarreto/notifications': typeof ApiZecarretoNotificationsRoute
  '/api/zecarreto/offers': typeof ApiZecarretoOffersRouteWithChildren
  '/api/zecarreto/payouts': typeof ApiZecarretoPayoutsRoute
  '/api/zecarreto/quotes': typeof ApiZecarretoQuotesRoute
  '/api/zecarreto/recommend': typeof ApiZecarretoRecommendRoute
  '/api/zecarreto/rides': typeof ApiZecarretoRidesRouteWithChildren
  '/api/zecarreto/wallet': typeof ApiZecarretoWalletRoute
  '/zecarreto/acompanhar/$token': typeof ZecarretoAcompanharTokenRoute
  '/zecarreto/admin/precos': typeof ZecarretoAdminPrecosRoute
  '/zecarreto/motorista/trabalho': typeof ZecarretoMotoristaTrabalhoRoute
  '/zecarreto/motorista/veiculos': typeof ZecarretoMotoristaVeiculosRoute
  '/zecarreto/pedido/$rideId': typeof ZecarretoPedidoRideIdRoute
  '/api/zecarreto/admin/addons': typeof ApiZecarretoAdminAddonsRoute
  '/api/zecarreto/admin/documents': typeof ApiZecarretoAdminDocumentsRouteWithChildren
  '/api/zecarreto/admin/drivers': typeof ApiZecarretoAdminDriversRouteWithChildren
  '/api/zecarreto/admin/history': typeof ApiZecarretoAdminHistoryRoute
  '/api/zecarreto/admin/rides': typeof ApiZecarretoAdminRidesRoute
  '/api/zecarreto/admin/settings': typeof ApiZecarretoAdminSettingsRoute
  '/api/zecarreto/admin/tariffs': typeof ApiZecarretoAdminTariffsRoute
  '/api/zecarreto/admin/vehicles': typeof ApiZecarretoAdminVehiclesRouteWithChildren
  '/api/zecarreto/auth/config': typeof ApiZecarretoAuthConfigRoute
  '/api/zecarreto/drivers/me': typeof ApiZecarretoDriversMeRouteWithChildren
  '/api/zecarreto/profile/addresses': typeof ApiZecarretoProfileAddressesRouteWithChildren
  '/api/zecarreto/profile/me': typeof ApiZecarretoProfileMeRoute
  '/api/zecarreto/profile/role': typeof ApiZecarretoProfileRoleRoute
  '/api/zecarreto/profile/terms': typeof ApiZecarretoProfileTermsRoute
  '/api/zecarreto/rides/$rideId': typeof ApiZecarretoRidesRideIdRouteWithChildren
  '/api/zecarreto/support/tickets': typeof ApiZecarretoSupportTicketsRouteWithChildren
  '/api/zecarreto/track/$token': typeof ApiZecarretoTrackTokenRoute
  '/api/zecarreto/uploads/sign': typeof ApiZecarretoUploadsSignRoute
  '/api/zecarreto/webhooks/payment': typeof ApiZecarretoWebhooksPaymentRoute
  '/api/public/menu-sync/$slug/$token': typeof ApiPublicMenuSyncSlugTokenRoute
  '/api/public/pizzerias/$slug/menu-sync': typeof ApiPublicPizzeriasSlugMenuSyncRoute
  '/api/zecarreto/admin/dispatch/recover': typeof ApiZecarretoAdminDispatchRecoverRoute
  '/api/zecarreto/admin/dispatch/tick': typeof ApiZecarretoAdminDispatchTickRoute
  '/api/zecarreto/admin/drivers/$driverId': typeof ApiZecarretoAdminDriversDriverIdRouteWithChildren
  '/api/zecarreto/admin/payouts/$payoutId': typeof ApiZecarretoAdminPayoutsPayoutIdRoute
  '/api/zecarreto/admin/payouts/close': typeof ApiZecarretoAdminPayoutsCloseRoute
  '/api/zecarreto/drivers/me/availability': typeof ApiZecarretoDriversMeAvailabilityRoute
  '/api/zecarreto/drivers/me/current': typeof ApiZecarretoDriversMeCurrentRoute
  '/api/zecarreto/drivers/me/documents': typeof ApiZecarretoDriversMeDocumentsRoute
  '/api/zecarreto/drivers/me/location': typeof ApiZecarretoDriversMeLocationRoute
  '/api/zecarreto/drivers/me/submit': typeof ApiZecarretoDriversMeSubmitRoute
  '/api/zecarreto/drivers/me/vehicles': typeof ApiZecarretoDriversMeVehiclesRouteWithChildren
  '/api/zecarreto/offers/$offerId/respond': typeof ApiZecarretoOffersOfferIdRespondRoute
  '/api/zecarreto/profile/addresses/$addressId': typeof ApiZecarretoProfileAddressesAddressIdRoute
  '/api/zecarreto/rides/$rideId/cancel': typeof ApiZecarretoRidesRideIdCancelRoute
  '/api/zecarreto/rides/$rideId/messages': typeof ApiZecarretoRidesRideIdMessagesRoute
  '/api/zecarreto/rides/$rideId/payment': typeof ApiZecarretoRidesRideIdPaymentRoute
  '/api/zecarreto/rides/$rideId/rating': typeof ApiZecarretoRidesRideIdRatingRoute
  '/api/zecarreto/rides/$rideId/release': typeof ApiZecarretoRidesRideIdReleaseRoute
  '/api/zecarreto/rides/$rideId/share': typeof ApiZecarretoRidesRideIdShareRoute
  '/api/zecarreto/rides/$rideId/status': typeof ApiZecarretoRidesRideIdStatusRoute
  '/api/zecarreto/rides/$rideId/track': typeof ApiZecarretoRidesRideIdTrackRoute
  '/api/zecarreto/support/tickets/$ticketId': typeof ApiZecarretoSupportTicketsTicketIdRoute
  '/api/zecarreto/admin/documents/$documentId/review': typeof ApiZecarretoAdminDocumentsDocumentIdReviewRoute
  '/api/zecarreto/admin/drivers/$driverId/reveal': typeof ApiZecarretoAdminDriversDriverIdRevealRoute
  '/api/zecarreto/admin/drivers/$driverId/review': typeof ApiZecarretoAdminDriversDriverIdReviewRoute
  '/api/zecarreto/admin/vehicles/$vehicleId/review': typeof ApiZecarretoAdminVehiclesVehicleIdReviewRoute
  '/api/zecarreto/drivers/me/vehicles/$vehicleId': typeof ApiZecarretoDriversMeVehiclesVehicleIdRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof SlugRoute
  '/debug-host': typeof DebugHostRoute
  '/login': typeof LoginRoute
  '/api/menu-sync': typeof ApiMenuSyncRouteWithChildren
  '/api/upload-image': typeof ApiUploadImageRoute
  '/zecarreto/admin': typeof ZecarretoAdminRouteWithChildren
  '/zecarreto/conta': typeof ZecarretoContaRoute
  '/zecarreto/enderecos': typeof ZecarretoEnderecosRoute
  '/zecarreto/entrar': typeof ZecarretoEntrarRoute
  '/zecarreto/motorista': typeof ZecarretoMotoristaRouteWithChildren
  '/zecarreto/pedir': typeof ZecarretoPedirRoute
  '/': typeof AuthenticatedIndexRoute
  '/zecarreto': typeof ZecarretoIndexRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
  '/export/$id': typeof AuthenticatedExportIdRoute
  '/api/internal/deprovision-restaurant': typeof ApiInternalDeprovisionRestaurantRoute
  '/api/internal/provision-restaurant': typeof ApiInternalProvisionRestaurantRoute
  '/api/menu-sync/$': typeof ApiMenuSyncSplatRoute
  '/api/public/check-table-session': typeof ApiPublicCheckTableSessionRoute
  '/api/public/flycontrol-table-closed': typeof ApiPublicFlycontrolTableClosedRoute
  '/api/public/open-table-session': typeof ApiPublicOpenTableSessionRoute
  '/api/public/request-close-table': typeof ApiPublicRequestCloseTableRoute
  '/api/public/submit-order': typeof ApiPublicSubmitOrderRoute
  '/api/zecarreto/catalog': typeof ApiZecarretoCatalogRoute
  '/api/zecarreto/geocode': typeof ApiZecarretoGeocodeRoute
  '/api/zecarreto/notifications': typeof ApiZecarretoNotificationsRoute
  '/api/zecarreto/offers': typeof ApiZecarretoOffersRouteWithChildren
  '/api/zecarreto/payouts': typeof ApiZecarretoPayoutsRoute
  '/api/zecarreto/quotes': typeof ApiZecarretoQuotesRoute
  '/api/zecarreto/recommend': typeof ApiZecarretoRecommendRoute
  '/api/zecarreto/rides': typeof ApiZecarretoRidesRouteWithChildren
  '/api/zecarreto/wallet': typeof ApiZecarretoWalletRoute
  '/zecarreto/acompanhar/$token': typeof ZecarretoAcompanharTokenRoute
  '/zecarreto/admin/precos': typeof ZecarretoAdminPrecosRoute
  '/zecarreto/motorista/trabalho': typeof ZecarretoMotoristaTrabalhoRoute
  '/zecarreto/motorista/veiculos': typeof ZecarretoMotoristaVeiculosRoute
  '/zecarreto/pedido/$rideId': typeof ZecarretoPedidoRideIdRoute
  '/api/zecarreto/admin/addons': typeof ApiZecarretoAdminAddonsRoute
  '/api/zecarreto/admin/documents': typeof ApiZecarretoAdminDocumentsRouteWithChildren
  '/api/zecarreto/admin/drivers': typeof ApiZecarretoAdminDriversRouteWithChildren
  '/api/zecarreto/admin/history': typeof ApiZecarretoAdminHistoryRoute
  '/api/zecarreto/admin/rides': typeof ApiZecarretoAdminRidesRoute
  '/api/zecarreto/admin/settings': typeof ApiZecarretoAdminSettingsRoute
  '/api/zecarreto/admin/tariffs': typeof ApiZecarretoAdminTariffsRoute
  '/api/zecarreto/admin/vehicles': typeof ApiZecarretoAdminVehiclesRouteWithChildren
  '/api/zecarreto/auth/config': typeof ApiZecarretoAuthConfigRoute
  '/api/zecarreto/drivers/me': typeof ApiZecarretoDriversMeRouteWithChildren
  '/api/zecarreto/profile/addresses': typeof ApiZecarretoProfileAddressesRouteWithChildren
  '/api/zecarreto/profile/me': typeof ApiZecarretoProfileMeRoute
  '/api/zecarreto/profile/role': typeof ApiZecarretoProfileRoleRoute
  '/api/zecarreto/profile/terms': typeof ApiZecarretoProfileTermsRoute
  '/api/zecarreto/rides/$rideId': typeof ApiZecarretoRidesRideIdRouteWithChildren
  '/api/zecarreto/support/tickets': typeof ApiZecarretoSupportTicketsRouteWithChildren
  '/api/zecarreto/track/$token': typeof ApiZecarretoTrackTokenRoute
  '/api/zecarreto/uploads/sign': typeof ApiZecarretoUploadsSignRoute
  '/api/zecarreto/webhooks/payment': typeof ApiZecarretoWebhooksPaymentRoute
  '/api/public/menu-sync/$slug/$token': typeof ApiPublicMenuSyncSlugTokenRoute
  '/api/public/pizzerias/$slug/menu-sync': typeof ApiPublicPizzeriasSlugMenuSyncRoute
  '/api/zecarreto/admin/dispatch/recover': typeof ApiZecarretoAdminDispatchRecoverRoute
  '/api/zecarreto/admin/dispatch/tick': typeof ApiZecarretoAdminDispatchTickRoute
  '/api/zecarreto/admin/drivers/$driverId': typeof ApiZecarretoAdminDriversDriverIdRouteWithChildren
  '/api/zecarreto/admin/payouts/$payoutId': typeof ApiZecarretoAdminPayoutsPayoutIdRoute
  '/api/zecarreto/admin/payouts/close': typeof ApiZecarretoAdminPayoutsCloseRoute
  '/api/zecarreto/drivers/me/availability': typeof ApiZecarretoDriversMeAvailabilityRoute
  '/api/zecarreto/drivers/me/current': typeof ApiZecarretoDriversMeCurrentRoute
  '/api/zecarreto/drivers/me/documents': typeof ApiZecarretoDriversMeDocumentsRoute
  '/api/zecarreto/drivers/me/location': typeof ApiZecarretoDriversMeLocationRoute
  '/api/zecarreto/drivers/me/submit': typeof ApiZecarretoDriversMeSubmitRoute
  '/api/zecarreto/drivers/me/vehicles': typeof ApiZecarretoDriversMeVehiclesRouteWithChildren
  '/api/zecarreto/offers/$offerId/respond': typeof ApiZecarretoOffersOfferIdRespondRoute
  '/api/zecarreto/profile/addresses/$addressId': typeof ApiZecarretoProfileAddressesAddressIdRoute
  '/api/zecarreto/rides/$rideId/cancel': typeof ApiZecarretoRidesRideIdCancelRoute
  '/api/zecarreto/rides/$rideId/messages': typeof ApiZecarretoRidesRideIdMessagesRoute
  '/api/zecarreto/rides/$rideId/payment': typeof ApiZecarretoRidesRideIdPaymentRoute
  '/api/zecarreto/rides/$rideId/rating': typeof ApiZecarretoRidesRideIdRatingRoute
  '/api/zecarreto/rides/$rideId/release': typeof ApiZecarretoRidesRideIdReleaseRoute
  '/api/zecarreto/rides/$rideId/share': typeof ApiZecarretoRidesRideIdShareRoute
  '/api/zecarreto/rides/$rideId/status': typeof ApiZecarretoRidesRideIdStatusRoute
  '/api/zecarreto/rides/$rideId/track': typeof ApiZecarretoRidesRideIdTrackRoute
  '/api/zecarreto/support/tickets/$ticketId': typeof ApiZecarretoSupportTicketsTicketIdRoute
  '/api/zecarreto/admin/documents/$documentId/review': typeof ApiZecarretoAdminDocumentsDocumentIdReviewRoute
  '/api/zecarreto/admin/drivers/$driverId/reveal': typeof ApiZecarretoAdminDriversDriverIdRevealRoute
  '/api/zecarreto/admin/drivers/$driverId/review': typeof ApiZecarretoAdminDriversDriverIdReviewRoute
  '/api/zecarreto/admin/vehicles/$vehicleId/review': typeof ApiZecarretoAdminVehiclesVehicleIdReviewRoute
  '/api/zecarreto/drivers/me/vehicles/$vehicleId': typeof ApiZecarretoDriversMeVehiclesVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$slug': typeof SlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/debug-host': typeof DebugHostRoute
  '/login': typeof LoginRoute
  '/api/menu-sync': typeof ApiMenuSyncRouteWithChildren
  '/api/upload-image': typeof ApiUploadImageRoute
  '/zecarreto/admin': typeof ZecarretoAdminRouteWithChildren
  '/zecarreto/conta': typeof ZecarretoContaRoute
  '/zecarreto/enderecos': typeof ZecarretoEnderecosRoute
  '/zecarreto/entrar': typeof ZecarretoEntrarRoute
  '/zecarreto/motorista': typeof ZecarretoMotoristaRouteWithChildren
  '/zecarreto/pedir': typeof ZecarretoPedirRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/zecarreto/': typeof ZecarretoIndexRoute
  '/_authenticated/edit/$id': typeof AuthenticatedEditIdRoute
  '/_authenticated/export/$id': typeof AuthenticatedExportIdRoute
  '/api/internal/deprovision-restaurant': typeof ApiInternalDeprovisionRestaurantRoute
  '/api/internal/provision-restaurant': typeof ApiInternalProvisionRestaurantRoute
  '/api/menu-sync/$': typeof ApiMenuSyncSplatRoute
  '/api/public/check-table-session': typeof ApiPublicCheckTableSessionRoute
  '/api/public/flycontrol-table-closed': typeof ApiPublicFlycontrolTableClosedRoute
  '/api/public/open-table-session': typeof ApiPublicOpenTableSessionRoute
  '/api/public/request-close-table': typeof ApiPublicRequestCloseTableRoute
  '/api/public/submit-order': typeof ApiPublicSubmitOrderRoute
  '/api/zecarreto/catalog': typeof ApiZecarretoCatalogRoute
  '/api/zecarreto/geocode': typeof ApiZecarretoGeocodeRoute
  '/api/zecarreto/notifications': typeof ApiZecarretoNotificationsRoute
  '/api/zecarreto/offers': typeof ApiZecarretoOffersRouteWithChildren
  '/api/zecarreto/payouts': typeof ApiZecarretoPayoutsRoute
  '/api/zecarreto/quotes': typeof ApiZecarretoQuotesRoute
  '/api/zecarreto/recommend': typeof ApiZecarretoRecommendRoute
  '/api/zecarreto/rides': typeof ApiZecarretoRidesRouteWithChildren
  '/api/zecarreto/wallet': typeof ApiZecarretoWalletRoute
  '/zecarreto/acompanhar/$token': typeof ZecarretoAcompanharTokenRoute
  '/zecarreto/admin/precos': typeof ZecarretoAdminPrecosRoute
  '/zecarreto/motorista/trabalho': typeof ZecarretoMotoristaTrabalhoRoute
  '/zecarreto/motorista/veiculos': typeof ZecarretoMotoristaVeiculosRoute
  '/zecarreto/pedido/$rideId': typeof ZecarretoPedidoRideIdRoute
  '/api/zecarreto/admin/addons': typeof ApiZecarretoAdminAddonsRoute
  '/api/zecarreto/admin/documents': typeof ApiZecarretoAdminDocumentsRouteWithChildren
  '/api/zecarreto/admin/drivers': typeof ApiZecarretoAdminDriversRouteWithChildren
  '/api/zecarreto/admin/history': typeof ApiZecarretoAdminHistoryRoute
  '/api/zecarreto/admin/rides': typeof ApiZecarretoAdminRidesRoute
  '/api/zecarreto/admin/settings': typeof ApiZecarretoAdminSettingsRoute
  '/api/zecarreto/admin/tariffs': typeof ApiZecarretoAdminTariffsRoute
  '/api/zecarreto/admin/vehicles': typeof ApiZecarretoAdminVehiclesRouteWithChildren
  '/api/zecarreto/auth/config': typeof ApiZecarretoAuthConfigRoute
  '/api/zecarreto/drivers/me': typeof ApiZecarretoDriversMeRouteWithChildren
  '/api/zecarreto/profile/addresses': typeof ApiZecarretoProfileAddressesRouteWithChildren
  '/api/zecarreto/profile/me': typeof ApiZecarretoProfileMeRoute
  '/api/zecarreto/profile/role': typeof ApiZecarretoProfileRoleRoute
  '/api/zecarreto/profile/terms': typeof ApiZecarretoProfileTermsRoute
  '/api/zecarreto/rides/$rideId': typeof ApiZecarretoRidesRideIdRouteWithChildren
  '/api/zecarreto/support/tickets': typeof ApiZecarretoSupportTicketsRouteWithChildren
  '/api/zecarreto/track/$token': typeof ApiZecarretoTrackTokenRoute
  '/api/zecarreto/uploads/sign': typeof ApiZecarretoUploadsSignRoute
  '/api/zecarreto/webhooks/payment': typeof ApiZecarretoWebhooksPaymentRoute
  '/api/public/menu-sync/$slug/$token': typeof ApiPublicMenuSyncSlugTokenRoute
  '/api/public/pizzerias/$slug/menu-sync': typeof ApiPublicPizzeriasSlugMenuSyncRoute
  '/api/zecarreto/admin/dispatch/recover': typeof ApiZecarretoAdminDispatchRecoverRoute
  '/api/zecarreto/admin/dispatch/tick': typeof ApiZecarretoAdminDispatchTickRoute
  '/api/zecarreto/admin/drivers/$driverId': typeof ApiZecarretoAdminDriversDriverIdRouteWithChildren
  '/api/zecarreto/admin/payouts/$payoutId': typeof ApiZecarretoAdminPayoutsPayoutIdRoute
  '/api/zecarreto/admin/payouts/close': typeof ApiZecarretoAdminPayoutsCloseRoute
  '/api/zecarreto/drivers/me/availability': typeof ApiZecarretoDriversMeAvailabilityRoute
  '/api/zecarreto/drivers/me/current': typeof ApiZecarretoDriversMeCurrentRoute
  '/api/zecarreto/drivers/me/documents': typeof ApiZecarretoDriversMeDocumentsRoute
  '/api/zecarreto/drivers/me/location': typeof ApiZecarretoDriversMeLocationRoute
  '/api/zecarreto/drivers/me/submit': typeof ApiZecarretoDriversMeSubmitRoute
  '/api/zecarreto/drivers/me/vehicles': typeof ApiZecarretoDriversMeVehiclesRouteWithChildren
  '/api/zecarreto/offers/$offerId/respond': typeof ApiZecarretoOffersOfferIdRespondRoute
  '/api/zecarreto/profile/addresses/$addressId': typeof ApiZecarretoProfileAddressesAddressIdRoute
  '/api/zecarreto/rides/$rideId/cancel': typeof ApiZecarretoRidesRideIdCancelRoute
  '/api/zecarreto/rides/$rideId/messages': typeof ApiZecarretoRidesRideIdMessagesRoute
  '/api/zecarreto/rides/$rideId/payment': typeof ApiZecarretoRidesRideIdPaymentRoute
  '/api/zecarreto/rides/$rideId/rating': typeof ApiZecarretoRidesRideIdRatingRoute
  '/api/zecarreto/rides/$rideId/release': typeof ApiZecarretoRidesRideIdReleaseRoute
  '/api/zecarreto/rides/$rideId/share': typeof ApiZecarretoRidesRideIdShareRoute
  '/api/zecarreto/rides/$rideId/status': typeof ApiZecarretoRidesRideIdStatusRoute
  '/api/zecarreto/rides/$rideId/track': typeof ApiZecarretoRidesRideIdTrackRoute
  '/api/zecarreto/support/tickets/$ticketId': typeof ApiZecarretoSupportTicketsTicketIdRoute
  '/api/zecarreto/admin/documents/$documentId/review': typeof ApiZecarretoAdminDocumentsDocumentIdReviewRoute
  '/api/zecarreto/admin/drivers/$driverId/reveal': typeof ApiZecarretoAdminDriversDriverIdRevealRoute
  '/api/zecarreto/admin/drivers/$driverId/review': typeof ApiZecarretoAdminDriversDriverIdReviewRoute
  '/api/zecarreto/admin/vehicles/$vehicleId/review': typeof ApiZecarretoAdminVehiclesVehicleIdReviewRoute
  '/api/zecarreto/drivers/me/vehicles/$vehicleId': typeof ApiZecarretoDriversMeVehiclesVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$slug'
    | '/'
    | '/debug-host'
    | '/login'
    | '/api/menu-sync'
    | '/api/upload-image'
    | '/zecarreto/admin'
    | '/zecarreto/conta'
    | '/zecarreto/enderecos'
    | '/zecarreto/entrar'
    | '/zecarreto/motorista'
    | '/zecarreto/pedir'
    | '/zecarreto/'
    | '/edit/$id'
    | '/export/$id'
    | '/api/internal/deprovision-restaurant'
    | '/api/internal/provision-restaurant'
    | '/api/menu-sync/$'
    | '/api/public/check-table-session'
    | '/api/public/flycontrol-table-closed'
    | '/api/public/open-table-session'
    | '/api/public/request-close-table'
    | '/api/public/submit-order'
    | '/api/zecarreto/catalog'
    | '/api/zecarreto/geocode'
    | '/api/zecarreto/notifications'
    | '/api/zecarreto/offers'
    | '/api/zecarreto/payouts'
    | '/api/zecarreto/quotes'
    | '/api/zecarreto/recommend'
    | '/api/zecarreto/rides'
    | '/api/zecarreto/wallet'
    | '/zecarreto/acompanhar/$token'
    | '/zecarreto/admin/precos'
    | '/zecarreto/motorista/trabalho'
    | '/zecarreto/motorista/veiculos'
    | '/zecarreto/pedido/$rideId'
    | '/api/zecarreto/admin/addons'
    | '/api/zecarreto/admin/documents'
    | '/api/zecarreto/admin/drivers'
    | '/api/zecarreto/admin/history'
    | '/api/zecarreto/admin/rides'
    | '/api/zecarreto/admin/settings'
    | '/api/zecarreto/admin/tariffs'
    | '/api/zecarreto/admin/vehicles'
    | '/api/zecarreto/auth/config'
    | '/api/zecarreto/drivers/me'
    | '/api/zecarreto/profile/addresses'
    | '/api/zecarreto/profile/me'
    | '/api/zecarreto/profile/role'
    | '/api/zecarreto/profile/terms'
    | '/api/zecarreto/rides/$rideId'
    | '/api/zecarreto/support/tickets'
    | '/api/zecarreto/track/$token'
    | '/api/zecarreto/uploads/sign'
    | '/api/zecarreto/webhooks/payment'
    | '/api/public/menu-sync/$slug/$token'
    | '/api/public/pizzerias/$slug/menu-sync'
    | '/api/zecarreto/admin/dispatch/recover'
    | '/api/zecarreto/admin/dispatch/tick'
    | '/api/zecarreto/admin/drivers/$driverId'
    | '/api/zecarreto/admin/payouts/$payoutId'
    | '/api/zecarreto/admin/payouts/close'
    | '/api/zecarreto/drivers/me/availability'
    | '/api/zecarreto/drivers/me/current'
    | '/api/zecarreto/drivers/me/documents'
    | '/api/zecarreto/drivers/me/location'
    | '/api/zecarreto/drivers/me/submit'
    | '/api/zecarreto/drivers/me/vehicles'
    | '/api/zecarreto/offers/$offerId/respond'
    | '/api/zecarreto/profile/addresses/$addressId'
    | '/api/zecarreto/rides/$rideId/cancel'
    | '/api/zecarreto/rides/$rideId/messages'
    | '/api/zecarreto/rides/$rideId/payment'
    | '/api/zecarreto/rides/$rideId/rating'
    | '/api/zecarreto/rides/$rideId/release'
    | '/api/zecarreto/rides/$rideId/share'
    | '/api/zecarreto/rides/$rideId/status'
    | '/api/zecarreto/rides/$rideId/track'
    | '/api/zecarreto/support/tickets/$ticketId'
    | '/api/zecarreto/admin/documents/$documentId/review'
    | '/api/zecarreto/admin/drivers/$driverId/reveal'
    | '/api/zecarreto/admin/drivers/$driverId/review'
    | '/api/zecarreto/admin/vehicles/$vehicleId/review'
    | '/api/zecarreto/drivers/me/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/debug-host'
    | '/login'
    | '/api/menu-sync'
    | '/api/upload-image'
    | '/zecarreto/admin'
    | '/zecarreto/conta'
    | '/zecarreto/enderecos'
    | '/zecarreto/entrar'
    | '/zecarreto/motorista'
    | '/zecarreto/pedir'
    | '/'
    | '/zecarreto'
    | '/edit/$id'
    | '/export/$id'
    | '/api/internal/deprovision-restaurant'
    | '/api/internal/provision-restaurant'
    | '/api/menu-sync/$'
    | '/api/public/check-table-session'
    | '/api/public/flycontrol-table-closed'
    | '/api/public/open-table-session'
    | '/api/public/request-close-table'
    | '/api/public/submit-order'
    | '/api/zecarreto/catalog'
    | '/api/zecarreto/geocode'
    | '/api/zecarreto/notifications'
    | '/api/zecarreto/offers'
    | '/api/zecarreto/payouts'
    | '/api/zecarreto/quotes'
    | '/api/zecarreto/recommend'
    | '/api/zecarreto/rides'
    | '/api/zecarreto/wallet'
    | '/zecarreto/acompanhar/$token'
    | '/zecarreto/admin/precos'
    | '/zecarreto/motorista/trabalho'
    | '/zecarreto/motorista/veiculos'
    | '/zecarreto/pedido/$rideId'
    | '/api/zecarreto/admin/addons'
    | '/api/zecarreto/admin/documents'
    | '/api/zecarreto/admin/drivers'
    | '/api/zecarreto/admin/history'
    | '/api/zecarreto/admin/rides'
    | '/api/zecarreto/admin/settings'
    | '/api/zecarreto/admin/tariffs'
    | '/api/zecarreto/admin/vehicles'
    | '/api/zecarreto/auth/config'
    | '/api/zecarreto/drivers/me'
    | '/api/zecarreto/profile/addresses'
    | '/api/zecarreto/profile/me'
    | '/api/zecarreto/profile/role'
    | '/api/zecarreto/profile/terms'
    | '/api/zecarreto/rides/$rideId'
    | '/api/zecarreto/support/tickets'
    | '/api/zecarreto/track/$token'
    | '/api/zecarreto/uploads/sign'
    | '/api/zecarreto/webhooks/payment'
    | '/api/public/menu-sync/$slug/$token'
    | '/api/public/pizzerias/$slug/menu-sync'
    | '/api/zecarreto/admin/dispatch/recover'
    | '/api/zecarreto/admin/dispatch/tick'
    | '/api/zecarreto/admin/drivers/$driverId'
    | '/api/zecarreto/admin/payouts/$payoutId'
    | '/api/zecarreto/admin/payouts/close'
    | '/api/zecarreto/drivers/me/availability'
    | '/api/zecarreto/drivers/me/current'
    | '/api/zecarreto/drivers/me/documents'
    | '/api/zecarreto/drivers/me/location'
    | '/api/zecarreto/drivers/me/submit'
    | '/api/zecarreto/drivers/me/vehicles'
    | '/api/zecarreto/offers/$offerId/respond'
    | '/api/zecarreto/profile/addresses/$addressId'
    | '/api/zecarreto/rides/$rideId/cancel'
    | '/api/zecarreto/rides/$rideId/messages'
    | '/api/zecarreto/rides/$rideId/payment'
    | '/api/zecarreto/rides/$rideId/rating'
    | '/api/zecarreto/rides/$rideId/release'
    | '/api/zecarreto/rides/$rideId/share'
    | '/api/zecarreto/rides/$rideId/status'
    | '/api/zecarreto/rides/$rideId/track'
    | '/api/zecarreto/support/tickets/$ticketId'
    | '/api/zecarreto/admin/documents/$documentId/review'
    | '/api/zecarreto/admin/drivers/$driverId/reveal'
    | '/api/zecarreto/admin/drivers/$driverId/review'
    | '/api/zecarreto/admin/vehicles/$vehicleId/review'
    | '/api/zecarreto/drivers/me/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/$slug'
    | '/_authenticated'
    | '/debug-host'
    | '/login'
    | '/api/menu-sync'
    | '/api/upload-image'
    | '/zecarreto/admin'
    | '/zecarreto/conta'
    | '/zecarreto/enderecos'
    | '/zecarreto/entrar'
    | '/zecarreto/motorista'
    | '/zecarreto/pedir'
    | '/_authenticated/'
    | '/zecarreto/'
    | '/_authenticated/edit/$id'
    | '/_authenticated/export/$id'
    | '/api/internal/deprovision-restaurant'
    | '/api/internal/provision-restaurant'
    | '/api/menu-sync/$'
    | '/api/public/check-table-session'
    | '/api/public/flycontrol-table-closed'
    | '/api/public/open-table-session'
    | '/api/public/request-close-table'
    | '/api/public/submit-order'
    | '/api/zecarreto/catalog'
    | '/api/zecarreto/geocode'
    | '/api/zecarreto/notifications'
    | '/api/zecarreto/offers'
    | '/api/zecarreto/payouts'
    | '/api/zecarreto/quotes'
    | '/api/zecarreto/recommend'
    | '/api/zecarreto/rides'
    | '/api/zecarreto/wallet'
    | '/zecarreto/acompanhar/$token'
    | '/zecarreto/admin/precos'
    | '/zecarreto/motorista/trabalho'
    | '/zecarreto/motorista/veiculos'
    | '/zecarreto/pedido/$rideId'
    | '/api/zecarreto/admin/addons'
    | '/api/zecarreto/admin/documents'
    | '/api/zecarreto/admin/drivers'
    | '/api/zecarreto/admin/history'
    | '/api/zecarreto/admin/rides'
    | '/api/zecarreto/admin/settings'
    | '/api/zecarreto/admin/tariffs'
    | '/api/zecarreto/admin/vehicles'
    | '/api/zecarreto/auth/config'
    | '/api/zecarreto/drivers/me'
    | '/api/zecarreto/profile/addresses'
    | '/api/zecarreto/profile/me'
    | '/api/zecarreto/profile/role'
    | '/api/zecarreto/profile/terms'
    | '/api/zecarreto/rides/$rideId'
    | '/api/zecarreto/support/tickets'
    | '/api/zecarreto/track/$token'
    | '/api/zecarreto/uploads/sign'
    | '/api/zecarreto/webhooks/payment'
    | '/api/public/menu-sync/$slug/$token'
    | '/api/public/pizzerias/$slug/menu-sync'
    | '/api/zecarreto/admin/dispatch/recover'
    | '/api/zecarreto/admin/dispatch/tick'
    | '/api/zecarreto/admin/drivers/$driverId'
    | '/api/zecarreto/admin/payouts/$payoutId'
    | '/api/zecarreto/admin/payouts/close'
    | '/api/zecarreto/drivers/me/availability'
    | '/api/zecarreto/drivers/me/current'
    | '/api/zecarreto/drivers/me/documents'
    | '/api/zecarreto/drivers/me/location'
    | '/api/zecarreto/drivers/me/submit'
    | '/api/zecarreto/drivers/me/vehicles'
    | '/api/zecarreto/offers/$offerId/respond'
    | '/api/zecarreto/profile/addresses/$addressId'
    | '/api/zecarreto/rides/$rideId/cancel'
    | '/api/zecarreto/rides/$rideId/messages'
    | '/api/zecarreto/rides/$rideId/payment'
    | '/api/zecarreto/rides/$rideId/rating'
    | '/api/zecarreto/rides/$rideId/release'
    | '/api/zecarreto/rides/$rideId/share'
    | '/api/zecarreto/rides/$rideId/status'
    | '/api/zecarreto/rides/$rideId/track'
    | '/api/zecarreto/support/tickets/$ticketId'
    | '/api/zecarreto/admin/documents/$documentId/review'
    | '/api/zecarreto/admin/drivers/$driverId/reveal'
    | '/api/zecarreto/admin/drivers/$driverId/review'
    | '/api/zecarreto/admin/vehicles/$vehicleId/review'
    | '/api/zecarreto/drivers/me/vehicles/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SlugRoute: typeof SlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DebugHostRoute: typeof DebugHostRoute
  LoginRoute: typeof LoginRoute
  ApiMenuSyncRoute: typeof ApiMenuSyncRouteWithChildren
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  ZecarretoAdminRoute: typeof ZecarretoAdminRouteWithChildren
  ZecarretoContaRoute: typeof ZecarretoContaRoute
  ZecarretoEnderecosRoute: typeof ZecarretoEnderecosRoute
  ZecarretoEntrarRoute: typeof ZecarretoEntrarRoute
  ZecarretoMotoristaRoute: typeof ZecarretoMotoristaRouteWithChildren
  ZecarretoPedirRoute: typeof ZecarretoPedirRoute
  ZecarretoIndexRoute: typeof ZecarretoIndexRoute
  ApiInternalDeprovisionRestaurantRoute: typeof ApiInternalDeprovisionRestaurantRoute
  ApiInternalProvisionRestaurantRoute: typeof ApiInternalProvisionRestaurantRoute
  ApiPublicCheckTableSessionRoute: typeof ApiPublicCheckTableSessionRoute
  ApiPublicFlycontrolTableClosedRoute: typeof ApiPublicFlycontrolTableClosedRoute
  ApiPublicOpenTableSessionRoute: typeof ApiPublicOpenTableSessionRoute
  ApiPublicRequestCloseTableRoute: typeof ApiPublicRequestCloseTableRoute
  ApiPublicSubmitOrderRoute: typeof ApiPublicSubmitOrderRoute
  ApiZecarretoCatalogRoute: typeof ApiZecarretoCatalogRoute
  ApiZecarretoGeocodeRoute: typeof ApiZecarretoGeocodeRoute
  ApiZecarretoNotificationsRoute: typeof ApiZecarretoNotificationsRoute
  ApiZecarretoOffersRoute: typeof ApiZecarretoOffersRouteWithChildren
  ApiZecarretoPayoutsRoute: typeof ApiZecarretoPayoutsRoute
  ApiZecarretoQuotesRoute: typeof ApiZecarretoQuotesRoute
  ApiZecarretoRecommendRoute: typeof ApiZecarretoRecommendRoute
  ApiZecarretoRidesRoute: typeof ApiZecarretoRidesRouteWithChildren
  ApiZecarretoWalletRoute: typeof ApiZecarretoWalletRoute
  ZecarretoAcompanharTokenRoute: typeof ZecarretoAcompanharTokenRoute
  ZecarretoPedidoRideIdRoute: typeof ZecarretoPedidoRideIdRoute
  ApiZecarretoAdminAddonsRoute: typeof ApiZecarretoAdminAddonsRoute
  ApiZecarretoAdminDocumentsRoute: typeof ApiZecarretoAdminDocumentsRouteWithChildren
  ApiZecarretoAdminDriversRoute: typeof ApiZecarretoAdminDriversRouteWithChildren
  ApiZecarretoAdminHistoryRoute: typeof ApiZecarretoAdminHistoryRoute
  ApiZecarretoAdminRidesRoute: typeof ApiZecarretoAdminRidesRoute
  ApiZecarretoAdminSettingsRoute: typeof ApiZecarretoAdminSettingsRoute
  ApiZecarretoAdminTariffsRoute: typeof ApiZecarretoAdminTariffsRoute
  ApiZecarretoAdminVehiclesRoute: typeof ApiZecarretoAdminVehiclesRouteWithChildren
  ApiZecarretoAuthConfigRoute: typeof ApiZecarretoAuthConfigRoute
  ApiZecarretoDriversMeRoute: typeof ApiZecarretoDriversMeRouteWithChildren
  ApiZecarretoProfileAddressesRoute: typeof ApiZecarretoProfileAddressesRouteWithChildren
  ApiZecarretoProfileMeRoute: typeof ApiZecarretoProfileMeRoute
  ApiZecarretoProfileRoleRoute: typeof ApiZecarretoProfileRoleRoute
  ApiZecarretoProfileTermsRoute: typeof ApiZecarretoProfileTermsRoute
  ApiZecarretoSupportTicketsRoute: typeof ApiZecarretoSupportTicketsRouteWithChildren
  ApiZecarretoTrackTokenRoute: typeof ApiZecarretoTrackTokenRoute
  ApiZecarretoUploadsSignRoute: typeof ApiZecarretoUploadsSignRoute
  ApiZecarretoWebhooksPaymentRoute: typeof ApiZecarretoWebhooksPaymentRoute
  ApiPublicMenuSyncSlugTokenRoute: typeof ApiPublicMenuSyncSlugTokenRoute
  ApiPublicPizzeriasSlugMenuSyncRoute: typeof ApiPublicPizzeriasSlugMenuSyncRoute
  ApiZecarretoAdminDispatchRecoverRoute: typeof ApiZecarretoAdminDispatchRecoverRoute
  ApiZecarretoAdminDispatchTickRoute: typeof ApiZecarretoAdminDispatchTickRoute
  ApiZecarretoAdminPayoutsPayoutIdRoute: typeof ApiZecarretoAdminPayoutsPayoutIdRoute
  ApiZecarretoAdminPayoutsCloseRoute: typeof ApiZecarretoAdminPayoutsCloseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-host': {
      id: '/debug-host'
      path: '/debug-host'
      fullPath: '/debug-host'
      preLoaderRoute: typeof DebugHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/menu-sync': {
      id: '/api/menu-sync'
      path: '/api/menu-sync'
      fullPath: '/api/menu-sync'
      preLoaderRoute: typeof ApiMenuSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zecarreto/': {
      id: '/zecarreto/'
      path: '/zecarreto'
      fullPath: '/zecarreto/'
      preLoaderRoute: typeof ZecarretoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zecarreto/admin': {
      id: '/zecarreto/admin'
      path: '/zecarreto/admin'
      fullPath: '/zecarreto/admin'
      preLoaderRoute: typeof ZecarretoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zecarreto/conta': {
      id: '/zecarreto/conta'
      path: '/zecarreto/conta'
      fullPath: '/zecarreto/conta'
      preLoaderRoute: typeof ZecarretoContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zecarreto/enderecos': {
      id: '/zecarreto/enderecos'
      path: '/zecarreto/enderecos'
      fullPath: '/zecarreto/enderecos'
      preLoaderRoute: typeof ZecarretoEnderecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zecarreto/entrar': {
      id: '/zecarreto/entrar'
      path: '/zecarreto/entrar'
      fullPath: '/zecarreto/entrar'
      preLoaderRoute: typeof ZecarretoEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zecarreto/motorista': {
      id: '/zecarreto/motorista'
      path: '/zecarreto/motorista'
      fullPath: '/zecarreto/motorista'
      preLoaderRoute: typeof ZecarretoMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zecarreto/pedir': {
      id: '/zecarreto/pedir'
      path: '/zecarreto/pedir'
      fullPath: '/zecarreto/pedir'
      preLoaderRoute: typeof ZecarretoPedirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/edit/$id': {
      id: '/_authenticated/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof AuthenticatedEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export/$id': {
      id: '/_authenticated/export/$id'
      path: '/export/$id'
      fullPath: '/export/$id'
      preLoaderRoute: typeof AuthenticatedExportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/internal/deprovision-restaurant': {
      id: '/api/internal/deprovision-restaurant'
      path: '/api/internal/deprovision-restaurant'
      fullPath: '/api/internal/deprovision-restaurant'
      preLoaderRoute: typeof ApiInternalDeprovisionRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/provision-restaurant': {
      id: '/api/internal/provision-restaurant'
      path: '/api/internal/provision-restaurant'
      fullPath: '/api/internal/provision-restaurant'
      preLoaderRoute: typeof ApiInternalProvisionRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu-sync/$': {
      id: '/api/menu-sync/$'
      path: '/$'
      fullPath: '/api/menu-sync/$'
      preLoaderRoute: typeof ApiMenuSyncSplatRouteImport
      parentRoute: typeof ApiMenuSyncRoute
    }
    '/api/public/check-table-session': {
      id: '/api/public/check-table-session'
      path: '/api/public/check-table-session'
      fullPath: '/api/public/check-table-session'
      preLoaderRoute: typeof ApiPublicCheckTableSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flycontrol-table-closed': {
      id: '/api/public/flycontrol-table-closed'
      path: '/api/public/flycontrol-table-closed'
      fullPath: '/api/public/flycontrol-table-closed'
      preLoaderRoute: typeof ApiPublicFlycontrolTableClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/open-table-session': {
      id: '/api/public/open-table-session'
      path: '/api/public/open-table-session'
      fullPath: '/api/public/open-table-session'
      preLoaderRoute: typeof ApiPublicOpenTableSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/request-close-table': {
      id: '/api/public/request-close-table'
      path: '/api/public/request-close-table'
      fullPath: '/api/public/request-close-table'
      preLoaderRoute: typeof ApiPublicRequestCloseTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-order': {
      id: '/api/public/submit-order'
      path: '/api/public/submit-order'
      fullPath: '/api/public/submit-order'
      preLoaderRoute: typeof ApiPublicSubmitOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/catalog': {
      id: '/api/zecarreto/catalog'
      path: '/api/zecarreto/catalog'
      fullPath: '/api/zecarreto/catalog'
      preLoaderRoute: typeof ApiZecarretoCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/geocode': {
      id: '/api/zecarreto/geocode'
      path: '/api/zecarreto/geocode'
      fullPath: '/api/zecarreto/geocode'
      preLoaderRoute: typeof ApiZecarretoGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/notifications': {
      id: '/api/zecarreto/notifications'
      path: '/api/zecarreto/notifications'
      fullPath: '/api/zecarreto/notifications'
      preLoaderRoute: typeof ApiZecarretoNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/offers': {
      id: '/api/zecarreto/offers'
      path: '/api/zecarreto/offers'
      fullPath: '/api/zecarreto/offers'
      preLoaderRoute: typeof ApiZecarretoOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/payouts': {
      id: '/api/zecarreto/payouts'
      path: '/api/zecarreto/payouts'
      fullPath: '/api/zecarreto/payouts'
      preLoaderRoute: typeof ApiZecarretoPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/quotes': {
      id: '/api/zecarreto/quotes'
      path: '/api/zecarreto/quotes'
      fullPath: '/api/zecarreto/quotes'
      preLoaderRoute: typeof ApiZecarretoQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/recommend': {
      id: '/api/zecarreto/recommend'
      path: '/api/zecarreto/recommend'
      fullPath: '/api/zecarreto/recommend'
      preLoaderRoute: typeof ApiZecarretoRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/rides': {
      id: '/api/zecarreto/rides'
      path: '/api/zecarreto/rides'
      fullPath: '/api/zecarreto/rides'
      preLoaderRoute: typeof ApiZecarretoRidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/wallet': {
      id: '/api/zecarreto/wallet'
      path: '/api/zecarreto/wallet'
      fullPath: '/api/zecarreto/wallet'
      preLoaderRoute: typeof ApiZecarretoWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zecarreto/acompanhar/$token': {
      id: '/zecarreto/acompanhar/$token'
      path: '/zecarreto/acompanhar/$token'
      fullPath: '/zecarreto/acompanhar/$token'
      preLoaderRoute: typeof ZecarretoAcompanharTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zecarreto/admin/precos': {
      id: '/zecarreto/admin/precos'
      path: '/precos'
      fullPath: '/zecarreto/admin/precos'
      preLoaderRoute: typeof ZecarretoAdminPrecosRouteImport
      parentRoute: typeof ZecarretoAdminRoute
    }
    '/zecarreto/motorista/trabalho': {
      id: '/zecarreto/motorista/trabalho'
      path: '/trabalho'
      fullPath: '/zecarreto/motorista/trabalho'
      preLoaderRoute: typeof ZecarretoMotoristaTrabalhoRouteImport
      parentRoute: typeof ZecarretoMotoristaRoute
    }
    '/zecarreto/motorista/veiculos': {
      id: '/zecarreto/motorista/veiculos'
      path: '/veiculos'
      fullPath: '/zecarreto/motorista/veiculos'
      preLoaderRoute: typeof ZecarretoMotoristaVeiculosRouteImport
      parentRoute: typeof ZecarretoMotoristaRoute
    }
    '/zecarreto/pedido/$rideId': {
      id: '/zecarreto/pedido/$rideId'
      path: '/zecarreto/pedido/$rideId'
      fullPath: '/zecarreto/pedido/$rideId'
      preLoaderRoute: typeof ZecarretoPedidoRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/addons': {
      id: '/api/zecarreto/admin/addons'
      path: '/api/zecarreto/admin/addons'
      fullPath: '/api/zecarreto/admin/addons'
      preLoaderRoute: typeof ApiZecarretoAdminAddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/documents': {
      id: '/api/zecarreto/admin/documents'
      path: '/api/zecarreto/admin/documents'
      fullPath: '/api/zecarreto/admin/documents'
      preLoaderRoute: typeof ApiZecarretoAdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/drivers': {
      id: '/api/zecarreto/admin/drivers'
      path: '/api/zecarreto/admin/drivers'
      fullPath: '/api/zecarreto/admin/drivers'
      preLoaderRoute: typeof ApiZecarretoAdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/history': {
      id: '/api/zecarreto/admin/history'
      path: '/api/zecarreto/admin/history'
      fullPath: '/api/zecarreto/admin/history'
      preLoaderRoute: typeof ApiZecarretoAdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/rides': {
      id: '/api/zecarreto/admin/rides'
      path: '/api/zecarreto/admin/rides'
      fullPath: '/api/zecarreto/admin/rides'
      preLoaderRoute: typeof ApiZecarretoAdminRidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/settings': {
      id: '/api/zecarreto/admin/settings'
      path: '/api/zecarreto/admin/settings'
      fullPath: '/api/zecarreto/admin/settings'
      preLoaderRoute: typeof ApiZecarretoAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/tariffs': {
      id: '/api/zecarreto/admin/tariffs'
      path: '/api/zecarreto/admin/tariffs'
      fullPath: '/api/zecarreto/admin/tariffs'
      preLoaderRoute: typeof ApiZecarretoAdminTariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/vehicles': {
      id: '/api/zecarreto/admin/vehicles'
      path: '/api/zecarreto/admin/vehicles'
      fullPath: '/api/zecarreto/admin/vehicles'
      preLoaderRoute: typeof ApiZecarretoAdminVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/auth/config': {
      id: '/api/zecarreto/auth/config'
      path: '/api/zecarreto/auth/config'
      fullPath: '/api/zecarreto/auth/config'
      preLoaderRoute: typeof ApiZecarretoAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/drivers/me': {
      id: '/api/zecarreto/drivers/me'
      path: '/api/zecarreto/drivers/me'
      fullPath: '/api/zecarreto/drivers/me'
      preLoaderRoute: typeof ApiZecarretoDriversMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/profile/addresses': {
      id: '/api/zecarreto/profile/addresses'
      path: '/api/zecarreto/profile/addresses'
      fullPath: '/api/zecarreto/profile/addresses'
      preLoaderRoute: typeof ApiZecarretoProfileAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/profile/me': {
      id: '/api/zecarreto/profile/me'
      path: '/api/zecarreto/profile/me'
      fullPath: '/api/zecarreto/profile/me'
      preLoaderRoute: typeof ApiZecarretoProfileMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/profile/role': {
      id: '/api/zecarreto/profile/role'
      path: '/api/zecarreto/profile/role'
      fullPath: '/api/zecarreto/profile/role'
      preLoaderRoute: typeof ApiZecarretoProfileRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/profile/terms': {
      id: '/api/zecarreto/profile/terms'
      path: '/api/zecarreto/profile/terms'
      fullPath: '/api/zecarreto/profile/terms'
      preLoaderRoute: typeof ApiZecarretoProfileTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/rides/$rideId': {
      id: '/api/zecarreto/rides/$rideId'
      path: '/$rideId'
      fullPath: '/api/zecarreto/rides/$rideId'
      preLoaderRoute: typeof ApiZecarretoRidesRideIdRouteImport
      parentRoute: typeof ApiZecarretoRidesRoute
    }
    '/api/zecarreto/support/tickets': {
      id: '/api/zecarreto/support/tickets'
      path: '/api/zecarreto/support/tickets'
      fullPath: '/api/zecarreto/support/tickets'
      preLoaderRoute: typeof ApiZecarretoSupportTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/track/$token': {
      id: '/api/zecarreto/track/$token'
      path: '/api/zecarreto/track/$token'
      fullPath: '/api/zecarreto/track/$token'
      preLoaderRoute: typeof ApiZecarretoTrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/uploads/sign': {
      id: '/api/zecarreto/uploads/sign'
      path: '/api/zecarreto/uploads/sign'
      fullPath: '/api/zecarreto/uploads/sign'
      preLoaderRoute: typeof ApiZecarretoUploadsSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/webhooks/payment': {
      id: '/api/zecarreto/webhooks/payment'
      path: '/api/zecarreto/webhooks/payment'
      fullPath: '/api/zecarreto/webhooks/payment'
      preLoaderRoute: typeof ApiZecarretoWebhooksPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/menu-sync/$slug/$token': {
      id: '/api/public/menu-sync/$slug/$token'
      path: '/api/public/menu-sync/$slug/$token'
      fullPath: '/api/public/menu-sync/$slug/$token'
      preLoaderRoute: typeof ApiPublicMenuSyncSlugTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pizzerias/$slug/menu-sync': {
      id: '/api/public/pizzerias/$slug/menu-sync'
      path: '/api/public/pizzerias/$slug/menu-sync'
      fullPath: '/api/public/pizzerias/$slug/menu-sync'
      preLoaderRoute: typeof ApiPublicPizzeriasSlugMenuSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/dispatch/recover': {
      id: '/api/zecarreto/admin/dispatch/recover'
      path: '/api/zecarreto/admin/dispatch/recover'
      fullPath: '/api/zecarreto/admin/dispatch/recover'
      preLoaderRoute: typeof ApiZecarretoAdminDispatchRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/dispatch/tick': {
      id: '/api/zecarreto/admin/dispatch/tick'
      path: '/api/zecarreto/admin/dispatch/tick'
      fullPath: '/api/zecarreto/admin/dispatch/tick'
      preLoaderRoute: typeof ApiZecarretoAdminDispatchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/drivers/$driverId': {
      id: '/api/zecarreto/admin/drivers/$driverId'
      path: '/$driverId'
      fullPath: '/api/zecarreto/admin/drivers/$driverId'
      preLoaderRoute: typeof ApiZecarretoAdminDriversDriverIdRouteImport
      parentRoute: typeof ApiZecarretoAdminDriversRoute
    }
    '/api/zecarreto/admin/payouts/$payoutId': {
      id: '/api/zecarreto/admin/payouts/$payoutId'
      path: '/api/zecarreto/admin/payouts/$payoutId'
      fullPath: '/api/zecarreto/admin/payouts/$payoutId'
      preLoaderRoute: typeof ApiZecarretoAdminPayoutsPayoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/admin/payouts/close': {
      id: '/api/zecarreto/admin/payouts/close'
      path: '/api/zecarreto/admin/payouts/close'
      fullPath: '/api/zecarreto/admin/payouts/close'
      preLoaderRoute: typeof ApiZecarretoAdminPayoutsCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zecarreto/drivers/me/availability': {
      id: '/api/zecarreto/drivers/me/availability'
      path: '/availability'
      fullPath: '/api/zecarreto/drivers/me/availability'
      preLoaderRoute: typeof ApiZecarretoDriversMeAvailabilityRouteImport
      parentRoute: typeof ApiZecarretoDriversMeRoute
    }
    '/api/zecarreto/drivers/me/current': {
      id: '/api/zecarreto/drivers/me/current'
      path: '/current'
      fullPath: '/api/zecarreto/drivers/me/current'
      preLoaderRoute: typeof ApiZecarretoDriversMeCurrentRouteImport
      parentRoute: typeof ApiZecarretoDriversMeRoute
    }
    '/api/zecarreto/drivers/me/documents': {
      id: '/api/zecarreto/drivers/me/documents'
      path: '/documents'
      fullPath: '/api/zecarreto/drivers/me/documents'
      preLoaderRoute: typeof ApiZecarretoDriversMeDocumentsRouteImport
      parentRoute: typeof ApiZecarretoDriversMeRoute
    }
    '/api/zecarreto/drivers/me/location': {
      id: '/api/zecarreto/drivers/me/location'
      path: '/location'
      fullPath: '/api/zecarreto/drivers/me/location'
      preLoaderRoute: typeof ApiZecarretoDriversMeLocationRouteImport
      parentRoute: typeof ApiZecarretoDriversMeRoute
    }
    '/api/zecarreto/drivers/me/submit': {
      id: '/api/zecarreto/drivers/me/submit'
      path: '/submit'
      fullPath: '/api/zecarreto/drivers/me/submit'
      preLoaderRoute: typeof ApiZecarretoDriversMeSubmitRouteImport
      parentRoute: typeof ApiZecarretoDriversMeRoute
    }
    '/api/zecarreto/drivers/me/vehicles': {
      id: '/api/zecarreto/drivers/me/vehicles'
      path: '/vehicles'
      fullPath: '/api/zecarreto/drivers/me/vehicles'
      preLoaderRoute: typeof ApiZecarretoDriversMeVehiclesRouteImport
      parentRoute: typeof ApiZecarretoDriversMeRoute
    }
    '/api/zecarreto/offers/$offerId/respond': {
      id: '/api/zecarreto/offers/$offerId/respond'
      path: '/$offerId/respond'
      fullPath: '/api/zecarreto/offers/$offerId/respond'
      preLoaderRoute: typeof ApiZecarretoOffersOfferIdRespondRouteImport
      parentRoute: typeof ApiZecarretoOffersRoute
    }
    '/api/zecarreto/profile/addresses/$addressId': {
      id: '/api/zecarreto/profile/addresses/$addressId'
      path: '/$addressId'
      fullPath: '/api/zecarreto/profile/addresses/$addressId'
      preLoaderRoute: typeof ApiZecarretoProfileAddressesAddressIdRouteImport
      parentRoute: typeof ApiZecarretoProfileAddressesRoute
    }
    '/api/zecarreto/rides/$rideId/cancel': {
      id: '/api/zecarreto/rides/$rideId/cancel'
      path: '/cancel'
      fullPath: '/api/zecarreto/rides/$rideId/cancel'
      preLoaderRoute: typeof ApiZecarretoRidesRideIdCancelRouteImport
      parentRoute: typeof ApiZecarretoRidesRideIdRoute
    }
    '/api/zecarreto/rides/$rideId/messages': {
      id: '/api/zecarreto/rides/$rideId/messages'
      path: '/messages'
      fullPath: '/api/zecarreto/rides/$rideId/messages'
      preLoaderRoute: typeof ApiZecarretoRidesRideIdMessagesRouteImport
      parentRoute: typeof ApiZecarretoRidesRideIdRoute
    }
    '/api/zecarreto/rides/$rideId/payment': {
      id: '/api/zecarreto/rides/$rideId/payment'
      path: '/payment'
      fullPath: '/api/zecarreto/rides/$rideId/payment'
      preLoaderRoute: typeof ApiZecarretoRidesRideIdPaymentRouteImport
      parentRoute: typeof ApiZecarretoRidesRideIdRoute
    }
    '/api/zecarreto/rides/$rideId/rating': {
      id: '/api/zecarreto/rides/$rideId/rating'
      path: '/rating'
      fullPath: '/api/zecarreto/rides/$rideId/rating'
      preLoaderRoute: typeof ApiZecarretoRidesRideIdRatingRouteImport
      parentRoute: typeof ApiZecarretoRidesRideIdRoute
    }
    '/api/zecarreto/rides/$rideId/release': {
      id: '/api/zecarreto/rides/$rideId/release'
      path: '/release'
      fullPath: '/api/zecarreto/rides/$rideId/release'
      preLoaderRoute: typeof ApiZecarretoRidesRideIdReleaseRouteImport
      parentRoute: typeof ApiZecarretoRidesRideIdRoute
    }
    '/api/zecarreto/rides/$rideId/share': {
      id: '/api/zecarreto/rides/$rideId/share'
      path: '/share'
      fullPath: '/api/zecarreto/rides/$rideId/share'
      preLoaderRoute: typeof ApiZecarretoRidesRideIdShareRouteImport
      parentRoute: typeof ApiZecarretoRidesRideIdRoute
    }
    '/api/zecarreto/rides/$rideId/status': {
      id: '/api/zecarreto/rides/$rideId/status'
      path: '/status'
      fullPath: '/api/zecarreto/rides/$rideId/status'
      preLoaderRoute: typeof ApiZecarretoRidesRideIdStatusRouteImport
      parentRoute: typeof ApiZecarretoRidesRideIdRoute
    }
    '/api/zecarreto/rides/$rideId/track': {
      id: '/api/zecarreto/rides/$rideId/track'
      path: '/track'
      fullPath: '/api/zecarreto/rides/$rideId/track'
      preLoaderRoute: typeof ApiZecarretoRidesRideIdTrackRouteImport
      parentRoute: typeof ApiZecarretoRidesRideIdRoute
    }
    '/api/zecarreto/support/tickets/$ticketId': {
      id: '/api/zecarreto/support/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/api/zecarreto/support/tickets/$ticketId'
      preLoaderRoute: typeof ApiZecarretoSupportTicketsTicketIdRouteImport
      parentRoute: typeof ApiZecarretoSupportTicketsRoute
    }
    '/api/zecarreto/admin/documents/$documentId/review': {
      id: '/api/zecarreto/admin/documents/$documentId/review'
      path: '/$documentId/review'
      fullPath: '/api/zecarreto/admin/documents/$documentId/review'
      preLoaderRoute: typeof ApiZecarretoAdminDocumentsDocumentIdReviewRouteImport
      parentRoute: typeof ApiZecarretoAdminDocumentsRoute
    }
    '/api/zecarreto/admin/drivers/$driverId/reveal': {
      id: '/api/zecarreto/admin/drivers/$driverId/reveal'
      path: '/reveal'
      fullPath: '/api/zecarreto/admin/drivers/$driverId/reveal'
      preLoaderRoute: typeof ApiZecarretoAdminDriversDriverIdRevealRouteImport
      parentRoute: typeof ApiZecarretoAdminDriversDriverIdRoute
    }
    '/api/zecarreto/admin/drivers/$driverId/review': {
      id: '/api/zecarreto/admin/drivers/$driverId/review'
      path: '/review'
      fullPath: '/api/zecarreto/admin/drivers/$driverId/review'
      preLoaderRoute: typeof ApiZecarretoAdminDriversDriverIdReviewRouteImport
      parentRoute: typeof ApiZecarretoAdminDriversDriverIdRoute
    }
    '/api/zecarreto/admin/vehicles/$vehicleId/review': {
      id: '/api/zecarreto/admin/vehicles/$vehicleId/review'
      path: '/$vehicleId/review'
      fullPath: '/api/zecarreto/admin/vehicles/$vehicleId/review'
      preLoaderRoute: typeof ApiZecarretoAdminVehiclesVehicleIdReviewRouteImport
      parentRoute: typeof ApiZecarretoAdminVehiclesRoute
    }
    '/api/zecarreto/drivers/me/vehicles/$vehicleId': {
      id: '/api/zecarreto/drivers/me/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/api/zecarreto/drivers/me/vehicles/$vehicleId'
      preLoaderRoute: typeof ApiZecarretoDriversMeVehiclesVehicleIdRouteImport
      parentRoute: typeof ApiZecarretoDriversMeVehiclesRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEditIdRoute: typeof AuthenticatedEditIdRoute
  AuthenticatedExportIdRoute: typeof AuthenticatedExportIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEditIdRoute: AuthenticatedEditIdRoute,
  AuthenticatedExportIdRoute: AuthenticatedExportIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiMenuSyncRouteChildren {
  ApiMenuSyncSplatRoute: typeof ApiMenuSyncSplatRoute
}

const ApiMenuSyncRouteChildren: ApiMenuSyncRouteChildren = {
  ApiMenuSyncSplatRoute: ApiMenuSyncSplatRoute,
}

const ApiMenuSyncRouteWithChildren = ApiMenuSyncRoute._addFileChildren(
  ApiMenuSyncRouteChildren,
)

interface ZecarretoAdminRouteChildren {
  ZecarretoAdminPrecosRoute: typeof ZecarretoAdminPrecosRoute
}

const ZecarretoAdminRouteChildren: ZecarretoAdminRouteChildren = {
  ZecarretoAdminPrecosRoute: ZecarretoAdminPrecosRoute,
}

const ZecarretoAdminRouteWithChildren = ZecarretoAdminRoute._addFileChildren(
  ZecarretoAdminRouteChildren,
)

interface ZecarretoMotoristaRouteChildren {
  ZecarretoMotoristaTrabalhoRoute: typeof ZecarretoMotoristaTrabalhoRoute
  ZecarretoMotoristaVeiculosRoute: typeof ZecarretoMotoristaVeiculosRoute
}

const ZecarretoMotoristaRouteChildren: ZecarretoMotoristaRouteChildren = {
  ZecarretoMotoristaTrabalhoRoute: ZecarretoMotoristaTrabalhoRoute,
  ZecarretoMotoristaVeiculosRoute: ZecarretoMotoristaVeiculosRoute,
}

const ZecarretoMotoristaRouteWithChildren =
  ZecarretoMotoristaRoute._addFileChildren(ZecarretoMotoristaRouteChildren)

interface ApiZecarretoOffersRouteChildren {
  ApiZecarretoOffersOfferIdRespondRoute: typeof ApiZecarretoOffersOfferIdRespondRoute
}

const ApiZecarretoOffersRouteChildren: ApiZecarretoOffersRouteChildren = {
  ApiZecarretoOffersOfferIdRespondRoute: ApiZecarretoOffersOfferIdRespondRoute,
}

const ApiZecarretoOffersRouteWithChildren =
  ApiZecarretoOffersRoute._addFileChildren(ApiZecarretoOffersRouteChildren)

interface ApiZecarretoRidesRideIdRouteChildren {
  ApiZecarretoRidesRideIdCancelRoute: typeof ApiZecarretoRidesRideIdCancelRoute
  ApiZecarretoRidesRideIdMessagesRoute: typeof ApiZecarretoRidesRideIdMessagesRoute
  ApiZecarretoRidesRideIdPaymentRoute: typeof ApiZecarretoRidesRideIdPaymentRoute
  ApiZecarretoRidesRideIdRatingRoute: typeof ApiZecarretoRidesRideIdRatingRoute
  ApiZecarretoRidesRideIdReleaseRoute: typeof ApiZecarretoRidesRideIdReleaseRoute
  ApiZecarretoRidesRideIdShareRoute: typeof ApiZecarretoRidesRideIdShareRoute
  ApiZecarretoRidesRideIdStatusRoute: typeof ApiZecarretoRidesRideIdStatusRoute
  ApiZecarretoRidesRideIdTrackRoute: typeof ApiZecarretoRidesRideIdTrackRoute
}

const ApiZecarretoRidesRideIdRouteChildren: ApiZecarretoRidesRideIdRouteChildren =
  {
    ApiZecarretoRidesRideIdCancelRoute: ApiZecarretoRidesRideIdCancelRoute,
    ApiZecarretoRidesRideIdMessagesRoute: ApiZecarretoRidesRideIdMessagesRoute,
    ApiZecarretoRidesRideIdPaymentRoute: ApiZecarretoRidesRideIdPaymentRoute,
    ApiZecarretoRidesRideIdRatingRoute: ApiZecarretoRidesRideIdRatingRoute,
    ApiZecarretoRidesRideIdReleaseRoute: ApiZecarretoRidesRideIdReleaseRoute,
    ApiZecarretoRidesRideIdShareRoute: ApiZecarretoRidesRideIdShareRoute,
    ApiZecarretoRidesRideIdStatusRoute: ApiZecarretoRidesRideIdStatusRoute,
    ApiZecarretoRidesRideIdTrackRoute: ApiZecarretoRidesRideIdTrackRoute,
  }

const ApiZecarretoRidesRideIdRouteWithChildren =
  ApiZecarretoRidesRideIdRoute._addFileChildren(
    ApiZecarretoRidesRideIdRouteChildren,
  )

interface ApiZecarretoRidesRouteChildren {
  ApiZecarretoRidesRideIdRoute: typeof ApiZecarretoRidesRideIdRouteWithChildren
}

const ApiZecarretoRidesRouteChildren: ApiZecarretoRidesRouteChildren = {
  ApiZecarretoRidesRideIdRoute: ApiZecarretoRidesRideIdRouteWithChildren,
}

const ApiZecarretoRidesRouteWithChildren =
  ApiZecarretoRidesRoute._addFileChildren(ApiZecarretoRidesRouteChildren)

interface ApiZecarretoAdminDocumentsRouteChildren {
  ApiZecarretoAdminDocumentsDocumentIdReviewRoute: typeof ApiZecarretoAdminDocumentsDocumentIdReviewRoute
}

const ApiZecarretoAdminDocumentsRouteChildren: ApiZecarretoAdminDocumentsRouteChildren =
  {
    ApiZecarretoAdminDocumentsDocumentIdReviewRoute:
      ApiZecarretoAdminDocumentsDocumentIdReviewRoute,
  }

const ApiZecarretoAdminDocumentsRouteWithChildren =
  ApiZecarretoAdminDocumentsRoute._addFileChildren(
    ApiZecarretoAdminDocumentsRouteChildren,
  )

interface ApiZecarretoAdminDriversDriverIdRouteChildren {
  ApiZecarretoAdminDriversDriverIdRevealRoute: typeof ApiZecarretoAdminDriversDriverIdRevealRoute
  ApiZecarretoAdminDriversDriverIdReviewRoute: typeof ApiZecarretoAdminDriversDriverIdReviewRoute
}

const ApiZecarretoAdminDriversDriverIdRouteChildren: ApiZecarretoAdminDriversDriverIdRouteChildren =
  {
    ApiZecarretoAdminDriversDriverIdRevealRoute:
      ApiZecarretoAdminDriversDriverIdRevealRoute,
    ApiZecarretoAdminDriversDriverIdReviewRoute:
      ApiZecarretoAdminDriversDriverIdReviewRoute,
  }

const ApiZecarretoAdminDriversDriverIdRouteWithChildren =
  ApiZecarretoAdminDriversDriverIdRoute._addFileChildren(
    ApiZecarretoAdminDriversDriverIdRouteChildren,
  )

interface ApiZecarretoAdminDriversRouteChildren {
  ApiZecarretoAdminDriversDriverIdRoute: typeof ApiZecarretoAdminDriversDriverIdRouteWithChildren
}

const ApiZecarretoAdminDriversRouteChildren: ApiZecarretoAdminDriversRouteChildren =
  {
    ApiZecarretoAdminDriversDriverIdRoute:
      ApiZecarretoAdminDriversDriverIdRouteWithChildren,
  }

const ApiZecarretoAdminDriversRouteWithChildren =
  ApiZecarretoAdminDriversRoute._addFileChildren(
    ApiZecarretoAdminDriversRouteChildren,
  )

interface ApiZecarretoAdminVehiclesRouteChildren {
  ApiZecarretoAdminVehiclesVehicleIdReviewRoute: typeof ApiZecarretoAdminVehiclesVehicleIdReviewRoute
}

const ApiZecarretoAdminVehiclesRouteChildren: ApiZecarretoAdminVehiclesRouteChildren =
  {
    ApiZecarretoAdminVehiclesVehicleIdReviewRoute:
      ApiZecarretoAdminVehiclesVehicleIdReviewRoute,
  }

const ApiZecarretoAdminVehiclesRouteWithChildren =
  ApiZecarretoAdminVehiclesRoute._addFileChildren(
    ApiZecarretoAdminVehiclesRouteChildren,
  )

interface ApiZecarretoDriversMeVehiclesRouteChildren {
  ApiZecarretoDriversMeVehiclesVehicleIdRoute: typeof ApiZecarretoDriversMeVehiclesVehicleIdRoute
}

const ApiZecarretoDriversMeVehiclesRouteChildren: ApiZecarretoDriversMeVehiclesRouteChildren =
  {
    ApiZecarretoDriversMeVehiclesVehicleIdRoute:
      ApiZecarretoDriversMeVehiclesVehicleIdRoute,
  }

const ApiZecarretoDriversMeVehiclesRouteWithChildren =
  ApiZecarretoDriversMeVehiclesRoute._addFileChildren(
    ApiZecarretoDriversMeVehiclesRouteChildren,
  )

interface ApiZecarretoDriversMeRouteChildren {
  ApiZecarretoDriversMeAvailabilityRoute: typeof ApiZecarretoDriversMeAvailabilityRoute
  ApiZecarretoDriversMeCurrentRoute: typeof ApiZecarretoDriversMeCurrentRoute
  ApiZecarretoDriversMeDocumentsRoute: typeof ApiZecarretoDriversMeDocumentsRoute
  ApiZecarretoDriversMeLocationRoute: typeof ApiZecarretoDriversMeLocationRoute
  ApiZecarretoDriversMeSubmitRoute: typeof ApiZecarretoDriversMeSubmitRoute
  ApiZecarretoDriversMeVehiclesRoute: typeof ApiZecarretoDriversMeVehiclesRouteWithChildren
}

const ApiZecarretoDriversMeRouteChildren: ApiZecarretoDriversMeRouteChildren = {
  ApiZecarretoDriversMeAvailabilityRoute:
    ApiZecarretoDriversMeAvailabilityRoute,
  ApiZecarretoDriversMeCurrentRoute: ApiZecarretoDriversMeCurrentRoute,
  ApiZecarretoDriversMeDocumentsRoute: ApiZecarretoDriversMeDocumentsRoute,
  ApiZecarretoDriversMeLocationRoute: ApiZecarretoDriversMeLocationRoute,
  ApiZecarretoDriversMeSubmitRoute: ApiZecarretoDriversMeSubmitRoute,
  ApiZecarretoDriversMeVehiclesRoute:
    ApiZecarretoDriversMeVehiclesRouteWithChildren,
}

const ApiZecarretoDriversMeRouteWithChildren =
  ApiZecarretoDriversMeRoute._addFileChildren(
    ApiZecarretoDriversMeRouteChildren,
  )

interface ApiZecarretoProfileAddressesRouteChildren {
  ApiZecarretoProfileAddressesAddressIdRoute: typeof ApiZecarretoProfileAddressesAddressIdRoute
}

const ApiZecarretoProfileAddressesRouteChildren: ApiZecarretoProfileAddressesRouteChildren =
  {
    ApiZecarretoProfileAddressesAddressIdRoute:
      ApiZecarretoProfileAddressesAddressIdRoute,
  }

const ApiZecarretoProfileAddressesRouteWithChildren =
  ApiZecarretoProfileAddressesRoute._addFileChildren(
    ApiZecarretoProfileAddressesRouteChildren,
  )

interface ApiZecarretoSupportTicketsRouteChildren {
  ApiZecarretoSupportTicketsTicketIdRoute: typeof ApiZecarretoSupportTicketsTicketIdRoute
}

const ApiZecarretoSupportTicketsRouteChildren: ApiZecarretoSupportTicketsRouteChildren =
  {
    ApiZecarretoSupportTicketsTicketIdRoute:
      ApiZecarretoSupportTicketsTicketIdRoute,
  }

const ApiZecarretoSupportTicketsRouteWithChildren =
  ApiZecarretoSupportTicketsRoute._addFileChildren(
    ApiZecarretoSupportTicketsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SlugRoute: SlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DebugHostRoute: DebugHostRoute,
  LoginRoute: LoginRoute,
  ApiMenuSyncRoute: ApiMenuSyncRouteWithChildren,
  ApiUploadImageRoute: ApiUploadImageRoute,
  ZecarretoAdminRoute: ZecarretoAdminRouteWithChildren,
  ZecarretoContaRoute: ZecarretoContaRoute,
  ZecarretoEnderecosRoute: ZecarretoEnderecosRoute,
  ZecarretoEntrarRoute: ZecarretoEntrarRoute,
  ZecarretoMotoristaRoute: ZecarretoMotoristaRouteWithChildren,
  ZecarretoPedirRoute: ZecarretoPedirRoute,
  ZecarretoIndexRoute: ZecarretoIndexRoute,
  ApiInternalDeprovisionRestaurantRoute: ApiInternalDeprovisionRestaurantRoute,
  ApiInternalProvisionRestaurantRoute: ApiInternalProvisionRestaurantRoute,
  ApiPublicCheckTableSessionRoute: ApiPublicCheckTableSessionRoute,
  ApiPublicFlycontrolTableClosedRoute: ApiPublicFlycontrolTableClosedRoute,
  ApiPublicOpenTableSessionRoute: ApiPublicOpenTableSessionRoute,
  ApiPublicRequestCloseTableRoute: ApiPublicRequestCloseTableRoute,
  ApiPublicSubmitOrderRoute: ApiPublicSubmitOrderRoute,
  ApiZecarretoCatalogRoute: ApiZecarretoCatalogRoute,
  ApiZecarretoGeocodeRoute: ApiZecarretoGeocodeRoute,
  ApiZecarretoNotificationsRoute: ApiZecarretoNotificationsRoute,
  ApiZecarretoOffersRoute: ApiZecarretoOffersRouteWithChildren,
  ApiZecarretoPayoutsRoute: ApiZecarretoPayoutsRoute,
  ApiZecarretoQuotesRoute: ApiZecarretoQuotesRoute,
  ApiZecarretoRecommendRoute: ApiZecarretoRecommendRoute,
  ApiZecarretoRidesRoute: ApiZecarretoRidesRouteWithChildren,
  ApiZecarretoWalletRoute: ApiZecarretoWalletRoute,
  ZecarretoAcompanharTokenRoute: ZecarretoAcompanharTokenRoute,
  ZecarretoPedidoRideIdRoute: ZecarretoPedidoRideIdRoute,
  ApiZecarretoAdminAddonsRoute: ApiZecarretoAdminAddonsRoute,
  ApiZecarretoAdminDocumentsRoute: ApiZecarretoAdminDocumentsRouteWithChildren,
  ApiZecarretoAdminDriversRoute: ApiZecarretoAdminDriversRouteWithChildren,
  ApiZecarretoAdminHistoryRoute: ApiZecarretoAdminHistoryRoute,
  ApiZecarretoAdminRidesRoute: ApiZecarretoAdminRidesRoute,
  ApiZecarretoAdminSettingsRoute: ApiZecarretoAdminSettingsRoute,
  ApiZecarretoAdminTariffsRoute: ApiZecarretoAdminTariffsRoute,
  ApiZecarretoAdminVehiclesRoute: ApiZecarretoAdminVehiclesRouteWithChildren,
  ApiZecarretoAuthConfigRoute: ApiZecarretoAuthConfigRoute,
  ApiZecarretoDriversMeRoute: ApiZecarretoDriversMeRouteWithChildren,
  ApiZecarretoProfileAddressesRoute:
    ApiZecarretoProfileAddressesRouteWithChildren,
  ApiZecarretoProfileMeRoute: ApiZecarretoProfileMeRoute,
  ApiZecarretoProfileRoleRoute: ApiZecarretoProfileRoleRoute,
  ApiZecarretoProfileTermsRoute: ApiZecarretoProfileTermsRoute,
  ApiZecarretoSupportTicketsRoute: ApiZecarretoSupportTicketsRouteWithChildren,
  ApiZecarretoTrackTokenRoute: ApiZecarretoTrackTokenRoute,
  ApiZecarretoUploadsSignRoute: ApiZecarretoUploadsSignRoute,
  ApiZecarretoWebhooksPaymentRoute: ApiZecarretoWebhooksPaymentRoute,
  ApiPublicMenuSyncSlugTokenRoute: ApiPublicMenuSyncSlugTokenRoute,
  ApiPublicPizzeriasSlugMenuSyncRoute: ApiPublicPizzeriasSlugMenuSyncRoute,
  ApiZecarretoAdminDispatchRecoverRoute: ApiZecarretoAdminDispatchRecoverRoute,
  ApiZecarretoAdminDispatchTickRoute: ApiZecarretoAdminDispatchTickRoute,
  ApiZecarretoAdminPayoutsPayoutIdRoute: ApiZecarretoAdminPayoutsPayoutIdRoute,
  ApiZecarretoAdminPayoutsCloseRoute: ApiZecarretoAdminPayoutsCloseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
